### Initial Imports and Data Splits

In [1]:
# import statements --> SOME OF THESE MAY NOT BE NEEDED
%matplotlib inline 
import numpy as np 

from matplotlib import pyplot as plt 
from matplotlib.cm import get_cmap
from matplotlib.ticker import StrMethodFormatter
from matplotlib.ticker import MultipleLocator
#from matplotlib.ticker import MaxNLocator
#import matplotlib.gridspec as gridspec
#import matplotlib.colors as mcolors
#import colorcet as cc
#from matplotlib.patches import Rectangle, FancyArrowPatch
#import matplotlib.ticker as ticker
#from mpl_toolkits.mplot3d import Axes3D
#from mpl_toolkits.axes_grid1 import make_axes_locatable
#import mpl_scatter_density
#from astropy.visualization import LogStretch
#from astropy.visualization.mpl_normalize import ImageNormalize

#import h5py

#from astropy.io import fits,ascii,votable
#from astropy import units as u 
#from astropy import constants as const
#from astropy import table
#from astropy.cosmology import Planck15,FlatLambdaCDM
#from astropy.table import Table

#from sklearn.cluster import KMeans 
#from sklearn import mixture
#from itertools import combinations
#from sklearn.neighbors import KNeighborsRegressor
#from sklearn.utils import check_array
#from sklearn.neighbors._base import _get_weights
#imports for TWO-NN
#import scipy
from sklearn import neighbors
#from sklearn import preprocessing

#import scipy.integrate
#from scipy.integrate import quad
#import numba
#from sklearn.datasets import load_digits
import umap
from umap.umap_ import nearest_neighbors
import pandas as pd
#import plotly
import plotly.express as px

#imports for plotly graphing
#import plotly.graph_objects as go
#from plotly.subplots import make_subplots

import pickle

pd.set_option('display.max_columns', None)

#BRETT NOTEBOOK IMPORTS
from pathlib import Path

from importlib import reload
import utils
reload(utils)
from minisom import MiniSom

# imports from animation_simplified2 notebook
import seaborn as sns
sns.set(style='white', rc={'figure.figsize':(14, 12), 'animation.html': 'html5'})
import os
import copy

/Users/finianashmead/miniconda3/envs/newmac1/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
import umapz2

In [3]:
data = pd.read_parquet('som_embeddings2M_260409.parquet')
spec95 = pd.read_parquet('spec95_ugrizyJH_maps_250819.parquet')
spec95 = spec95.drop(columns=['SOM-1', 'SOM-2', 'UMAP3D-1', 'UMAP3D-2', 'UMAP3D-3'])
spec95 = spec95[spec95['specz']>0.0]
spec95 = pd.merge(left=spec95[['ID', 'specz']], right=data, left_on='ID', right_on='ID')
spec95

,ID,specz,RA,DEC,FLAG_COMBINED,CFHT_u_FLUX,CFHT_u_FLUXERR,CFHT_u_MAGERR,HSC_g_FLUX,HSC_g_FLUXERR,HSC_g_MAGERR,HSC_r_FLUX,HSC_r_FLUXERR,HSC_r_MAGERR,HSC_i_FLUX,HSC_i_FLUXERR,HSC_i_MAGERR,HSC_z_FLUX,HSC_z_FLUXERR,HSC_z_MAGERR,HSC_y_FLUX,HSC_y_FLUXERR,HSC_y_MAGERR,UVISTA_J_FLUX,UVISTA_J_FLUXERR,UVISTA_J_MAGERR,UVISTA_H_FLUX,UVISTA_H_FLUXERR,UVISTA_H_MAGERR,UVISTA_Ks_FLUX,UVISTA_Ks_FLUXERR,UVISTA_Ks_MAGERR,IRAC_CH1_FLUX,IRAC_CH1_FLUXERR,IRAC_CH1_MAGERR,IRAC_CH2_FLUX,IRAC_CH2_FLUXERR,IRAC_CH2_MAGERR,lp_photoz,lp_type,lp_zp_2,lp_NbFilt,lp_zq,lp_model,lp_age,lp_dust,lp_Attenuation,lp_MNUV,lp_MR,lp_MJ,lp_mass_med,lp_mass_med_min68,lp_mass_med_max68,lp_mass_best,lp_SFR_med,lp_sSFR_best,CFHT_u_MAG,HSC_g_MAG,HSC_r_MAG,HSC_i_MAG,HSC_z_MAG,HSC_y_MAG,UVISTA_J_MAG,UVISTA_H_MAG,UVISTA_Ks_MAG,IRAC_CH1_MAG,IRAC_CH2_MAG,u-g,g-r,r-i,i-z,z-y,y-J,J-H,SOM_46_92_s0.85_lr0.68-1,SOM_46_92_s0.85_lr0.68-2,SOM_46_92_s0.85_lr0.8-1,SOM_46_92_s0.85_lr0.8-2,SOM_46_92_s0.85_lr0.92-1,SOM_46_92_s0.85_lr0.92-2,SOM_46_92_s1_lr0.68-1,SOM_46_92_s1_lr0.68-2,SOM_46_92_s1_lr0.8-1,SOM_46_92_s1_lr0.8-2,SOM_46_92_s1_lr0.92-1,SOM_46_92_s1_lr0.92-2,SOM_46_92_s1.15_lr0.68-1,SOM_46_92_s1.15_lr0.68-2,SOM_46_92_s1.15_lr0.8-1,SOM_46_92_s1.15_lr0.8-2,SOM_46_92_s1.15_lr0.92-1,SOM_46_92_s1.15_lr0.92-2,SOM_50_100_s0.85_lr0.68-1,SOM_50_100_s0.85_lr0.68-2,SOM_50_100_s0.85_lr0.8-1,SOM_50_100_s0.85_lr0.8-2,SOM_50_100_s0.85_lr0.92-1,SOM_50_100_s0.85_lr0.92-2,SOM_50_100_s1_lr0.68-1,SOM_50_100_s1_lr0.68-2,SOM_50_100_s1_lr0.8-1,SOM_50_100_s1_lr0.8-2,SOM_50_100_s1_lr0.92-1,SOM_50_100_s1_lr0.92-2,SOM_50_100_s1.15_lr0.68-1,SOM_50_100_s1.15_lr0.68-2,SOM_50_100_s1.15_lr0.8-1,SOM_50_100_s1.15_lr0.8-2,SOM_50_100_s1.15_lr0.92-1,SOM_50_100_s1.15_lr0.92-2,SOM_54_108_s0.85_lr0.68-1,SOM_54_108_s0.85_lr0.68-2,SOM_54_108_s0.85_lr0.8-1,SOM_54_108_s0.85_lr0.8-2,SOM_54_108_s0.85_lr0.92-1,SOM_54_108_s0.85_lr0.92-2,SOM_54_108_s1_lr0.68-1,SOM_54_108_s1_lr0.68-2,SOM_54_108_s1_lr0.8-1,SOM_54_108_s1_lr0.8-2,SOM_54_108_s1_lr0.92-1,SOM_54_108_s1_lr0.92-2,SOM_54_108_s1.15_lr0.68-1,SOM_54_108_s1.15_lr0.68-2,SOM_54_108_s1.15_lr0.8-1,SOM_54_108_s1.15_lr0.8-2,SOM_54_108_s1.15_lr0.92-1,SOM_54_108_s1.15_lr0.92-2
0,535,0.82589,150.726526,1.795723,0,3.135322,0.004911,0.001979,3.543392,0.005600,0.001707,4.149280,0.006839,0.001707,5.531073,0.006686,0.001311,9.094858,0.011055,0.001310,6.137582,0.023292,0.003891,8.654985,0.055195,0.006917,8.847195,0.061729,0.007971,10.089081,0.037653,0.004077,12.819075,0.017958,0.001854,8.697933,0.024042,0.003679,0.8165,0,NaN,28,1.85,8,1.609000e+08,0.2,1,-20.28363,-21.12927,-21.52369,9.31240,9.27122,9.34644,9.33645,1.23468,-8.087,22.659295,22.526452,22.355068,22.042977,21.503010,21.930007,21.556834,21.532986,21.390371,21.130358,21.551460,0.132843,0.171384,0.312092,0.539966,-0.426997,0.373173,0.023848,17,53,9,54,15,54,18,52,9,60,12,51,15,55,11,62,14,79,14,96,35,94,21,31,9,35,44,15,11,45,14,43,15,24,11,33,50,93,50,83,8,5,49,88,53,88,53,86,31,18,49,90,51,89
1,670,1.16549,149.730259,1.959835,0,1.941518,0.005379,0.003476,1.863746,0.004178,0.002408,2.359093,0.005581,0.002440,3.347864,0.005832,0.001883,4.712861,0.009339,0.002130,5.044670,0.019908,0.004038,5.936375,0.013675,0.002495,7.337306,0.017588,0.002736,9.483263,0.026426,0.003042,13.707825,0.014322,0.001382,12.806878,0.012845,0.001335,1.1792,0,NaN,30,1.02,10,2.273000e+08,0.3,0,-20.49749,-21.89549,-22.47231,9.79095,9.75692,9.83047,9.80739,1.80017,-7.953,23.179647,23.224033,22.968137,22.588081,22.216789,22.142918,21.966197,21.736158,21.457606,21.057579,21.131392,-0.044386,0.255896,0.380057,0.371292,0.073870,0.176721,0.230038,8,47,27,17,9,79,9,58,16,45,9,64,5,33,37,38,10,61,33,8,12,41,12,43,5,36,3,93,36,13,30,19,22,6,37,5,20,34,50,50,50,43,36,38,27,22,24,86,43,102,10,106,22,6
2,692,0.30572,149.642181,2.379960,0,1.315313,0.006756,0.006467,4.484449,0.005892,0.001415,13.213070,0.007819,0.000612,24.048380,0.008534,0.000384,35.020987,0.013526,0.000416,40.134805,0.026583,0.000678,66.579523,0.061359,0.000999,98.679499,0.078428,0.000908,133.665136,0.058089,0.000475,81.719072,0.032358,0.000524,83.615927,0.028347,0.000451,0.3269,0,NaN,29,0.29,9,5.000000e+09,0.4,1,-16.72223,-20.57175,-21.94677,10.35539,10.31772,10.39305,10.38281,0.19029,-10.190,23.602427,22.270727,21.097491,20.447285,20.039179,19.891197,19.341648,18.914433,18.584955,19.119191,19.094277,1.331700,1.173237,0.650205,0.408106,0.147982,0.549549,0.427216,10,3,28,78,38,15,25,7,44,13,12,28,34,79,20,20,27,9,24,45,26,47,38,76,29,34,37,38,30,51,28,68,10,76,16,76,4,62,3,48,41,61,14,70,20,72,1,63,13,69,34,50,15,52
3,1143,0.80030,150.589033,1.889879,0,0.063290,0.003653,0.072636,0.254108,0.004009,0.016990,1.155916,0.005216,0.004662,4.069362,0.005549,0.001476,6.650530,0.009029,0.001461,8.661979,0.019250,0.002276,14.262715,0.022103,0.001680,23.028622,0.020338,0.001009,32.456397,0.027529,0.000926,NaN,NaN,NaN,26.183528,0.044004,0.002237,0.7986,0,NaN,28,0.64,1,2.000000e+09,0.0,0,-16.79230,-21.67922,-22.74348,10.34975,10.31558,10.38392,10.32480,-6.09950,-16.440,26.896659,25.387452,23.742684,22.376184,21.842859,21.555957,21.014494,20.494330,20.121749,NaN,20.354930,1.509207,1.644768,1.366500,0.533325,0.286902,0.541463,0.520164,39,70,41,71,31,2,39,75,42,3,44,81,43,68,44,84,40,87,39,44,41,43,40,73,35,44,38,47,31,44,44,74,44,50,35,48,34,72,37,103,33,65,8,63,29,66,28,53,33,63,31,62,32,67
4,1245,1.23815,149.971382,1.711330,0,1.695707,0.006863,0.005056,1.691740,0.005530,0.003500,2.357181,0.007089,0.003094,3.366750,0.007567,0.002425,5.704886,0.012347,0.002323,6.829482,0.025867,0.003871,9.471108,0.059377,0.006786,13.002449,0.077023,0.006759,18.572509,0.051679,0.003037,29.470112,0.016731,0.000751,28.078737,0.017725,0.000840,1.2540,0,NaN,29,1.09,7,2.600000e+09,0.2,0,-20.53407,-22.57335,-23.39578,10.59188,10.55031,10.64044,10.62809,1.40000,-9.214,23.326623,23.329166,22.969017,22.581973,22.009383,21.814031,21.458998,21.114937,20.727824,20.226546,20.279056,-0.002543,0.360149,0.387045,0.572590,0.195352,0.355033,0.344061,39,45,40,38,31,38,38,43,27,54,31,8,27,14,31,11,30,34,31,2,33,3,3,8,36,19,21,5,29,21,40,27,14,9,48,21,49,40,32,79,38,90,23,105,27,38,32,87,42,93,24,97,16,36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14472,964293,0.30882,150.197702,1.791536,0,7.815364,0.012754,0.002038,18.310474,0.009038,0.000528,45.964169,0.012306,0.000275,74.019787,0.013086,0.000191,97.404310,0.021407,0.000236,109.393904,0.038414,0.000359,154.071989,0.025450,0.000179,200.484768,0.034710,0.000198,238.176555,0.050933,0.000233,137.774089,0.016902,0.000162,123.599561,0.018025,0.000194,0.3154,0,NaN,30,0.34,9,5.500000e+09,0.1,0,-18.72000,-21.66386,-22.62620,10.65000,10.61600,10.68400,10.61871,0.30000,-10.370,21.667627,20.743251,19.743951,19.226630,18.928555,18.802517,18.430691,18.144797,17.957752,18.552081,18.669958,0.924376,0.999300,0.517321,0.298076,0.126037,0.371826,0.285894,39,86,27,78,30,16,26,64,43,19,26,77,34,83,33,83,27,12,41,54,27,52,40,82,24,47,37,33,31,55,16,57,41,58,21,77,25,60,24,44,48,62,8,40,11,71,41,53,27,76,34,46,12,51
14473,964308,0.80880,150.189166,1.786760,0,0.376955,0.007829,0.025939,1.125239,0.004581,0.004358,4.881146,0.006761,0.001425,16.260245,0.007515,0.000499,27.009426,0.012383,0.000492,32.401518,0.022967,0.000724,51.259633,0.015446,0.000326,72.215790,0.020729,0.000327,94.934133,0.030071,0.000346,116.689012,0.012641,0.000143,77.455344,0.013697,0.000235,0.8244,0,NaN,29,0.68,2,2.300000e+09,0.0,0,-18.47022,-23.15855,-23.98529,11.00000,10.96600,11.03400,10.98945,-0.60000,-11.560,24.959276,23.771888,22.178695,20.872182,20.321212,20.123587,19.625561,19.253420,18.956444,18.732425,19.177372,1.187388,1.593193,1.306513,0.550971,0.197625,0.498025,0.372142,41,66,41,77,43,76,42,78,37,3,40,85,44,72,41,89,39,84,42,43,40,49,36,71,38,46,45,50,41,44,41,73,39,48,34,47,35,74,44,101,31,64,6,65,36,62,35,57,35,62,35,65,39,69
14474,964377,0.34094,149.971501,2.459277,0,0.781867,0.006094,0.009706,4.248786,0.004722,0.001187,16.713592,0.007689,0.000472,31.840775,0.008043,0.000272,42.508116,0.012185,0.000307,51.027704,0.021628,0.000433,77.996092,0.039856,0.000553,113.188162,0.053447,0.000539,141.624981,0.037039,0.000285,73.498912,0.025304,0.000455,58.364998,0.027856,0.000635,0.4349,0,NaN,29,0.32,3,6.500000e+09,0.0,0,-17.31676,-21.65651,-22.77276,10.83808,10.53309,10.88018,10.81345,-0.72385,-11.550,24.167168,22.329338,20.842326,20.142541,19.828820,19.630485,19.169818,18.765497,18.522150,19.234298,19.484619,1.837830,1.487012,0.699785,0.313721,0.198335,0.460667,0.404320,42,78,31,71,28,9,34,66,13,1,39,78,34,72,15,22,20,6,33,49,40,33,47,71,14,75,30,41,3,62,12,65,14,74,18,70,7,56,10,59,43,66,7,51,17,66,7,57,18,67,24,53,19,57
14475,964392,0.89240,149.926987,2.376219,0,1.002968,0.007177,0.008954,1.022032,0.005433,0.005699,1.378424,0.007239,0.005408,2.395704,0.007750,0.003493,2.969146,0.012144,0.004393,3.190317,0.025382,0.008135,4.197636,0.051640,0.013321,3.960244,0.068713,0.019800,4.311192,0.049579,0.012554,4.892384,0.016271,0.004400,3.330375,0.016820,0.006720,0.8828,0,NaN,28,1.88,6,5.088000e+08,0.2,1,-19.11129,-20.53859,-20.77834,9.33938,9.30075,9.38472,9.34513,0.79998,-8.569,23.896782,23.876339,23.551543,22.951417,22.718421,22.640415,22.342488,22.405695,22.313507,22.176199,22.593767,0.020444,0.324796,0.600126,0.232996,0.078006,0.297927,-0.063207,13,50,43,21,10,82,7,49,19,78,22,46,17,41,11,52,44,24,47,89,42,88,42,29,48,3,22,66,45,3,41,38,25,23,18,13,1,85,48,64,32,30,51,76,36,14,21,30,21,32,44,95,31,29
14476,964399,0.82590,150.446456,2.041975,0,1.441391,0.007583,0.006564,1.475838,0.005284,0.003829,1.847675,0.006822,0.003796,2.743945,0.007632,0.003000,4.584578,0.012381,0.002898,3.132128,0.025927,0.008457,4.516743,0.019004,0.004553,4.403745,0.024753,0.006412,4.610646,0.034778,0.008232,6.041300,0.015501,0.003394,4.991077,0.016769,0.004470,0.7699,0,NaN,29,1.85,9,1.278000e+08,0.3,0,-19.20053,-20.59380,-20.53390,9.05020,9.01606,9.08420,9.04790,1.30000,-7.731,23.503045,23.477403,23.233436,22.804062,22.246752,22.660401,22.262937,22.290445,22.240596,21.947174,22.154514,0.025642,0.243967,0.429374,0.557310,-0.413649,0.397465,-0.027508,10,59,8,60,15,54,13,53,10,60,12,51,15,55,11,61,13,83,13,95,35,94,21,35,13,38,42,17,12,44,13,43,15,24,12,35,51,88,50,80,5,5,49,88,21,13,52,83,28,19,49,90,51,89

In [4]:
z_cut = 1.5

In [5]:
len(data) - len(data[data['lp_photoz']>0.0])

0

In [6]:
#spec95.to_parquet('umap_embeddings_spec.parquet')

In [7]:
splits = umapz2.data_split(photcat=data, speccat=spec95, valid_size=len(spec95), rs=41)

In [8]:
valid = splits['valid'].copy()
valid

,ID,RA,DEC,FLAG_COMBINED,CFHT_u_FLUX,CFHT_u_FLUXERR,CFHT_u_MAGERR,HSC_g_FLUX,HSC_g_FLUXERR,HSC_g_MAGERR,HSC_r_FLUX,HSC_r_FLUXERR,HSC_r_MAGERR,HSC_i_FLUX,HSC_i_FLUXERR,HSC_i_MAGERR,HSC_z_FLUX,HSC_z_FLUXERR,HSC_z_MAGERR,HSC_y_FLUX,HSC_y_FLUXERR,HSC_y_MAGERR,UVISTA_J_FLUX,UVISTA_J_FLUXERR,UVISTA_J_MAGERR,UVISTA_H_FLUX,UVISTA_H_FLUXERR,UVISTA_H_MAGERR,UVISTA_Ks_FLUX,UVISTA_Ks_FLUXERR,UVISTA_Ks_MAGERR,IRAC_CH1_FLUX,IRAC_CH1_FLUXERR,IRAC_CH1_MAGERR,IRAC_CH2_FLUX,IRAC_CH2_FLUXERR,IRAC_CH2_MAGERR,lp_photoz,lp_type,lp_zp_2,lp_NbFilt,lp_zq,lp_model,lp_age,lp_dust,lp_Attenuation,lp_MNUV,lp_MR,lp_MJ,lp_mass_med,lp_mass_med_min68,lp_mass_med_max68,lp_mass_best,lp_SFR_med,lp_sSFR_best,CFHT_u_MAG,HSC_g_MAG,HSC_r_MAG,HSC_i_MAG,HSC_z_MAG,HSC_y_MAG,UVISTA_J_MAG,UVISTA_H_MAG,UVISTA_Ks_MAG,IRAC_CH1_MAG,IRAC_CH2_MAG,u-g,g-r,r-i,i-z,z-y,y-J,J-H,SOM_46_92_s0.85_lr0.68-1,SOM_46_92_s0.85_lr0.68-2,SOM_46_92_s0.85_lr0.8-1,SOM_46_92_s0.85_lr0.8-2,SOM_46_92_s0.85_lr0.92-1,SOM_46_92_s0.85_lr0.92-2,SOM_46_92_s1_lr0.68-1,SOM_46_92_s1_lr0.68-2,SOM_46_92_s1_lr0.8-1,SOM_46_92_s1_lr0.8-2,SOM_46_92_s1_lr0.92-1,SOM_46_92_s1_lr0.92-2,SOM_46_92_s1.15_lr0.68-1,SOM_46_92_s1.15_lr0.68-2,SOM_46_92_s1.15_lr0.8-1,SOM_46_92_s1.15_lr0.8-2,SOM_46_92_s1.15_lr0.92-1,SOM_46_92_s1.15_lr0.92-2,SOM_50_100_s0.85_lr0.68-1,SOM_50_100_s0.85_lr0.68-2,SOM_50_100_s0.85_lr0.8-1,SOM_50_100_s0.85_lr0.8-2,SOM_50_100_s0.85_lr0.92-1,SOM_50_100_s0.85_lr0.92-2,SOM_50_100_s1_lr0.68-1,SOM_50_100_s1_lr0.68-2,SOM_50_100_s1_lr0.8-1,SOM_50_100_s1_lr0.8-2,SOM_50_100_s1_lr0.92-1,SOM_50_100_s1_lr0.92-2,SOM_50_100_s1.15_lr0.68-1,SOM_50_100_s1.15_lr0.68-2,SOM_50_100_s1.15_lr0.8-1,SOM_50_100_s1.15_lr0.8-2,SOM_50_100_s1.15_lr0.92-1,SOM_50_100_s1.15_lr0.92-2,SOM_54_108_s0.85_lr0.68-1,SOM_54_108_s0.85_lr0.68-2,SOM_54_108_s0.85_lr0.8-1,SOM_54_108_s0.85_lr0.8-2,SOM_54_108_s0.85_lr0.92-1,SOM_54_108_s0.85_lr0.92-2,SOM_54_108_s1_lr0.68-1,SOM_54_108_s1_lr0.68-2,SOM_54_108_s1_lr0.8-1,SOM_54_108_s1_lr0.8-2,SOM_54_108_s1_lr0.92-1,SOM_54_108_s1_lr0.92-2,SOM_54_108_s1.15_lr0.68-1,SOM_54_108_s1.15_lr0.68-2,SOM_54_108_s1.15_lr0.8-1,SOM_54_108_s1.15_lr0.8-2,SOM_54_108_s1.15_lr0.92-1,SOM_54_108_s1.15_lr0.92-2
682744,888967,149.936450,2.785401,0,0.482169,0.008109,0.021217,0.556797,0.004353,0.008433,0.649724,0.005866,0.009340,0.815287,0.006075,0.008074,1.022175,0.009601,0.010115,1.516981,0.023160,0.015645,2.479349,0.054714,0.023929,3.181551,0.075771,0.027204,3.775385,0.057224,0.016556,5.577980,0.014766,0.003503,6.055261,0.017200,0.003780,1.5429,0,NaN,27,0.99,5,1.139000e+09,0.2,0,-19.84784,-21.53190,-22.12276,10.02579,9.89337,10.08403,10.03590,1.14004,-8.917,24.692001,24.535758,24.368177,24.121724,23.876187,23.447549,22.914156,22.643403,22.457597,22.033808,21.944668,0.156243,0.167580,0.246453,0.245537,0.428638,0.533394,0.270753,33,16,18,34,23,41,29,23,7,73,25,31,33,34,26,42,39,13,24,88,21,91,31,11,35,87,21,94,14,85,17,94,44,86,10,88,18,93,15,93,35,103,40,100,17,103,36,106,25,99,39,104,28,100
705718,915989,150.389923,1.791782,0,0.300923,0.003346,0.013912,0.391560,0.003238,0.008863,0.729946,0.004244,0.005987,0.857738,0.004264,0.005368,0.908493,0.006994,0.008269,1.053736,0.015095,0.014646,1.133205,0.028540,0.027268,1.063807,0.038095,0.040864,1.151679,0.027239,0.025818,0.553292,0.012940,0.030942,0.312715,0.016622,0.070726,0.4445,0,NaN,30,0.00,1,3.210000e+08,0.0,0,-16.35030,-17.63879,-17.70557,8.08427,8.02849,8.19774,8.06536,-1.17000,-9.212,25.203863,24.918003,24.241773,24.066614,24.004195,23.843171,23.764228,23.832843,23.746671,24.542615,25.162128,0.285860,0.676230,0.175160,0.062418,0.161025,0.078942,-0.068615,7,89,6,22,7,29,22,54,2,36,12,39,16,83,11,81,10,90,12,51,30,70,2,45,12,49,7,56,40,71,46,52,36,79,43,69,37,105,2,17,40,49,2,0,5,15,5,22,45,34,6,16,4,19
132564,175014,150.121155,1.644934,0,0.281661,0.003567,0.015858,0.294709,0.003148,0.011457,0.385362,0.004180,0.011174,0.606247,0.004185,0.007456,0.866615,0.006661,0.008258,0.800703,0.015264,0.019495,0.987316,0.013438,0.014739,0.996477,0.017941,0.020548,0.986751,0.026845,0.029699,0.839995,0.013123,0.020670,0.550881,0.013868,0.033498,0.8564,0,NaN,29,0.00,7,1.015000e+09,0.1,1,-17.75778,-18.94959,-19.07940,8.71424,8.66864,8.75055,8.73949,-0.09519,-8.830,25.275684,25.226517,24.935328,24.443377,24.055434,24.141322,23.913860,23.903831,23.914481,24.089309,24.547356,0.049166,0.291189,0.491951,0.387943,-0.085888,0.227462,0.010028,13,49,6,56,17,51,12,48,15,58,17,54,18,41,3,64,16,81,22,18,42,87,19,26,13,16,14,24,12,24,20,31,49,5,43,5,40,34,24,35,5,31,47,84,15,7,23,85,12,101,49,100,26,7
38676,53915,150.365002,2.127347,0,0.467036,0.006094,0.016220,0.526304,0.004793,0.009714,0.840886,0.006087,0.007426,1.706182,0.006378,0.004026,2.390468,0.010503,0.004710,2.376359,0.021343,0.009167,3.818460,0.042345,0.011993,4.366636,0.056518,0.014759,5.914739,0.041212,0.007602,7.887154,0.016861,0.002828,6.016602,0.020844,0.004609,0.8240,0,NaN,29,0.74,3,5.709000e+08,0.3,0,-18.17301,-20.26624,-20.98757,9.55956,9.51840,9.59472,9.53026,0.81388,-8.720,24.726624,24.596909,24.088157,23.319937,22.953793,22.960220,22.445280,22.299632,21.970161,21.657699,21.951622,0.129714,0.508752,0.768220,0.366144,-0.006427,0.514941,0.145647,25,55,10,46,45,50,39,18,45,63,33,1,17,9,27,52,32,21,32,81,7,13,41,39,6,2,2,3,27,25,23,35,38,21,15,35,47,85,34,69,38,37,50,67,48,84,22,38,18,105,52,79,45,42
739250,954912,149.888388,2.290574,0,0.826631,0.005465,0.008313,1.289190,0.004453,0.003717,2.720754,0.005884,0.002233,5.181314,0.006121,0.001278,6.401118,0.009896,0.001663,7.309192,0.020159,0.002824,9.951759,0.058052,0.006322,13.869990,0.071990,0.005926,19.369627,0.040532,0.002285,21.725130,0.017028,0.001037,15.774899,0.016255,0.001371,0.7021,0,NaN,29,0.67,7,5.088000e+08,0.5,1,-18.45950,-20.96760,-21.87276,9.88231,9.84503,9.92537,9.84081,1.30000,-8.550,24.106721,23.624208,22.813277,22.113900,21.884360,21.740327,21.405250,21.044810,20.682197,20.557594,20.905084,0.482513,0.810931,0.699377,0.229540,0.144034,0.335076,0.360441,2,3,26,7,3,10,33,52,35,21,23,70,25,52,28,69,27,81,21,34,44,21,20,79,33,58,7,11,40,82,32,63,27,51,27,81,33,83,1,71,45,82,1,82,45,76,10,75,40,78,38,43,27,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
684584,891138,150.110471,1.777353,0,0.296048,0.005221,0.021937,0.312364,0.003521,0.012030,0.508558,0.004627,0.009337,0.829878,0.004729,0.006138,1.036933,0.007572,0.007828,1.030603,0.016646,0.016488,1.247287,0.012057,0.010455,1.467359,0.016032,0.012459,1.553659,0.023101,0.016223,1.349267,0.009179,0.008999,0.898451,0.010706,0.015853,0.7395,0,NaN,29,0.00,7,1.015000e+09,0.2,1,-17.33409,-18.99425,-19.25434,8.82421,8.78011,8.86880,8.85254,0.00044,-8.830,25.221593,25.163349,24.634149,24.102465,23.860623,23.867272,23.660084,23.483659,23.421611,23.574755,24.016264,0.058244,0.529201,0.531684,0.241842,-0.006649,0.207188,0.176425,18,81,40,11,26,57,15,81,28,81,37,6,12,16,15,62,20,76,15,17,43,81,40,32,5,7,13,22,11,30,11,46,46,14,43,93,37,41,21,29,4,76,43,79,35,9,16,84,32,34,18,33,44,97
427923,571071,150.772739,1.921325,0,0.724656,0.005547,0.009648,0.917149,0.004717,0.005544,1.590404,0.006477,0.004211,3.466228,0.006843,0.002138,5.315191,0.011298,0.002288,6.166483,0.024737,0.004110,8.671765,0.054305,0.006790,12.070129,0.071572,0.006772,16.333579,0.045231,0.003025,22.720054,0.022136,0.001289,17.737899,0.026435,0.001983,0.9833,0,NaN,29,0.94,9,2.300000e+09,0.3,1,-19.22390,-21.64550,-22.48912,10.30044,10.26566,10.33554,10.29149,1.10086,-9.248,24.249670,23.993900,23.396231,22.550357,22.086203,21.924906,21.554731,21.195720,20.867297,20.508977,20.777745,0.255770,0.597669,0.845874,0.464154,0.161297,0.370175,0.359011,26,53,44,46,28,77,37,49,35,72,30,55,20,5,30,49,41,45,38,82,10,14,15,13,16,3,9,3,45,23,1,71,48,22,27,86,49,57,45,88,41,86,44,64,53,76,48,71,43,80,8,90,28,41
599855,790913,150.055650,2.681121,0,0.222790,0.007355,0.041457,0.232116,0.004918,0.022777,0.450094,0.006607,0.015146,0.993257,0.006998,0.007619,1.775239,0.011250,0.006814,2.260605,0.024694,0.011180,3.981098,0.014831,0.004036,6.266626,0.019997,0.003643,9.861777,0.031682,0.003508,16.374265,0.033513,0.002708,14.218412,0.029937,0.002802,1.0852,0,NaN,29,1.04,10,1.609000e+09,0.5,0,-18.02475,-21.23968,-22.28055,10.24881,10.19431,10.33383,10.23888,1.35714,-8.800,25.530263,25.485736,24.766743,23.907346,23.276858,23.014438,22.399993,21.907416,21.415112,20.864595,21.017872,0.044527,0.718994,0.859397,0.630487,0.262420,0.614445,0.492577,44,51,35,44,29,76,38,0,35,89,28,5,36,5,31,1,44,46,40,24,29,2,49,43,42,25,11,0,34,27,31,93,33,35,37,30,53,79,33,86,16,40,35,52,47,48,33,82,53,70,33,84,50,73
104,187,150.727327,1.794051,0,1.077269,0.004572,0.005362,1.322689,0.004821,0.003937,1.380330,0.006299,0.004726,1.514137,0.006054,0.004335,1.726628,0.009914,0.006186,2.687333,0.021823,0.008325,2.992035,0.053495,0.019393,3.628191,0.059291,0.018670,3.787613,0.034818,0.010042,4.799319,0.018039,0.004974,5.398208,0.023180,0.005715,1.5271,0,NaN,28,2.35,12,1.805000e+08,0.2,0,-20.65049,-21.56226,-21.92586,9.43635,9.40054,9.48063,9.45094,1.59673,-7.857,23.819190,23.596356,23.550043,23.449587,23.307003,22.826696,22.710083,22.500775,22.454086,22.197051,22.069376,0.222834,0.046313,0.100456,0.142584,0.480307,0.116613,0.209309,14,32,20,38,19,42,19,24,28,30,30,30,18,30,43,19,44,12,48,64,21,90,31,16,25,83,18,97,30,90,13,95,44,91,12,93,13,0,11,93,25,105,41,107,36,102,31,104,37,106,33,106,31,102
542415,720423,150.463695,1.769475,0,0.534084,0.003426,0.008043,0.571298,0.003826,0.007190,0.695724,0.004837,0.007168,1.286778,0.005075,0.004263,1.629097,0.008167,0.005388,1.747869,0.018093,0.010590,2.216999,0.012493,0.006103,2.293473,0.016460,0.008192,2.446169,0.023374,0.010432,2.563994,0.015923,0.008217,2.031265,0.018048,0.011823,0.9002,0,NaN,30,0.00,5,4.535000e+08,0.2,0,-18.56275,-19.88653,-20.19196,9.17963,9.13639,9.22567,9.13358,0.60714,-8.520,24.580977,24.507844,24.293907,23.626241,23.370133,23.293728,23.035586,22.998766,22.928784,22.877707,23.130584,0.073133,0.213937,0.667666,0.256108,0.076405,0.258142,0.036820,23,29,43,17,18,78,6,50,37,57,20,44,15,42,13,52,33,27,47,89,43,6,40,29,44,10,45,83,44,1,42,39,31,15,22,22,4,34,43,37,22,30,52,50,33,13,47,40,25,26,3,97,27,18

### Uncertainty Quantification Procedure:
The validation set (14,477 objects) contains only 2370 objects at z > 1.5. Correspondingly, and illustrative of the spectroscopic bias, the spectroscopic set (likewise 14,477 objects) contains only 989 objects at z > 1.5. With such small numbers to work with, and considering that we are not re-optimizing any parameters for this test, we will adopt the uncertainties on global performance metrics attributable to +/-15% parameter value choices from our full-sample analysis. 

For the uncertainties attributable to random seed variations and finite test set size (bootstrap resampling), we will implement a cut on the LePHARE redshifts ('lp_photoz') of the test objects of z > 1.5 before calculating the performance metrics. 

4. Uncertainty associated with random seed variations. Mean and standard deviations of 
   performance metrics calculated using 25 random seeds with fixed SOM parameters.
    
5. Uncertainty due to finite test data can be calculated with 10-25 bootstrap samples of 
   the size of the test set, with replacement. Measure all statistics and look at 
   standard deviation in redshift bins. This is for fixed SOM parameters and random seed.

### SOM-z:

for paper: SOM-rm-z --> "nearest-z" ; SOM-tco-z --> "SOM-z"

load in uncertainties associated with hyperparameter optimization:

In [9]:
with open("colors_global_260513.pkl", "rb") as f:
    colors_global = pickle.load(f)

colors_unc_kg_outliers = colors_global['LePHARE_trained']['f_outlier']['unc_k']
colors_unc_kg_nmads = colors_global['LePHARE_trained']['nmad']['unc_k']
colors_unc_kg_biases = colors_global['LePHARE_trained']['bias']['unc_k']

In [10]:
with open("umap_global_260727.pkl", "rb") as f:
    umap_global = pickle.load(f)

umap_unc_kg_outliers = umap_global['LePHARE_trained']['f_outlier']['unc_k']
umap_unc_kg_nmads = umap_global['LePHARE_trained']['nmad']['unc_k']
umap_unc_kg_biases = umap_global['LePHARE_trained']['bias']['unc_k']

umap_unc_nng_outliers = umap_global['LePHARE_trained']['f_outlier']['unc_nn']
umap_unc_nng_nmads = umap_global['LePHARE_trained']['nmad']['unc_nn']
umap_unc_nng_biases = umap_global['LePHARE_trained']['bias']['unc_nn']

In [11]:
with open("somz_global_260727.pkl", "rb") as f:
    somtco_global = pickle.load(f)

somtco_unc_sizeg_outliers = somtco_global['LePHARE_trained']['f_outlier']['unc_size']
somtco_unc_sizeg_nmads = somtco_global['LePHARE_trained']['nmad']['unc_size']
somtco_unc_sizeg_biases = somtco_global['LePHARE_trained']['bias']['unc_size']

somtco_unc_sigmag_outliers = somtco_global['LePHARE_trained']['f_outlier']['unc_sigma']
somtco_unc_sigmag_nmads = somtco_global['LePHARE_trained']['nmad']['unc_sigma']
somtco_unc_sigmag_biases = somtco_global['LePHARE_trained']['bias']['unc_sigma']

somtco_unc_lrg_outliers = somtco_global['LePHARE_trained']['f_outlier']['unc_learning_rate']
somtco_unc_lrg_nmads = somtco_global['LePHARE_trained']['nmad']['unc_learning_rate']
somtco_unc_lrg_biases = somtco_global['LePHARE_trained']['bias']['unc_learning_rate']

#### uncertainty due to different random seeds

In [12]:
som_rs_data = pd.read_parquet('som_rs25_maps_manhattan_260509.parquet') 
umap_rs_data = pd.read_parquet('umap_nn70_rs25_260523.parquet')

In [13]:
som_rs_spec = pd.merge(som_rs_data.copy()[som_rs_data['ID'].isin(spec95['ID'])], spec95[['ID', 'specz']], left_on='ID', right_on='ID', how='left')
somrm_rs_test = som_rs_data.copy()[som_rs_data['ID'].isin(splits['test_spec']['ID'])]
somrm_rs_test_lp = som_rs_data.copy()[som_rs_data['ID'].isin(splits['test_lp']['ID'])]
som_rs_train_lp = som_rs_data.copy()[som_rs_data['ID'].isin(splits['train_lp']['ID'])]
somtco_rs_test = somrm_rs_test.copy()
somtco_rs_test_lp = somrm_rs_test_lp.copy()

umap_rs_spec = pd.merge(umap_rs_data.copy()[umap_rs_data['ID'].isin(spec95['ID'])], spec95[['ID', 'specz']], left_on='ID', right_on='ID', how='left')
umap_rs_test = umap_rs_data.copy()[umap_rs_data['ID'].isin(splits['test_spec']['ID'])]
umap_rs_test_lp = umap_rs_data.copy()[umap_rs_data['ID'].isin(splits['test_lp']['ID'])]
umap_rs_train_lp = umap_rs_data.copy()[umap_rs_data['ID'].isin(splits['train_lp']['ID'])]

colors_test_lp = splits['test_lp'].copy()
colors_test_s = splits['test_spec'].copy()
colors_train_lp = splits['train_lp'].copy()
colors_train_s = splits['train_spec'].copy()

In [14]:
n_embeddings=25

som_testcats_s = []
som_testcats_lp = []

somtco_outliers_rs = []
somtco_nmads_rs = []
somtco_biases_rs = []

somtco_outliers_rs_lp = []
somtco_nmads_rs_lp = []
somtco_biases_rs_lp = []

umap_outliers_rs = []
umap_nmads_rs = []
umap_biases_rs = []

umap_outliers_rs_lp = []
umap_nmads_rs_lp = []
umap_biases_rs_lp = []

colors_outliers_rs = []
colors_nmads_rs = []
colors_biases_rs = []

colors_outliers_rs_lp = []
colors_nmads_rs_lp = []
colors_biases_rs_lp = []

# for colors, we only run once (no different-random-seeds step involved)
# to account for different trained/untrained SOM cells in each rs case, just 
# recalculate colors performance for each SOM case
colors_test_s['TEST_Z'] = umapz2.interpolator_colors(df1=colors_train_s, df2=colors_test_s, coords=['u-g', 'g-r', 'r-i', 'i-z', 
                                    'z-y', 'y-J', 'J-H'], nn=11, calc='median', z_true='specz', p=1).copy()['TEST_Z']
colors_test_s = colors_test_s.copy()[colors_test_s['lp_photoz']>z_cut]
colors_test_lp['TEST_Z'] = umapz2.interpolator_colors(df1=colors_train_lp, df2=colors_test_lp, coords=['u-g', 'g-r', 'r-i', 'i-z', 
                                    'z-y', 'y-J', 'J-H'], nn=11, calc='median', z_true='lp_photoz', p=1).copy()['TEST_Z']
colors_test_lp = colors_test_lp.copy()[colors_test_lp['lp_photoz']>z_cut]

for i in range(n_embeddings):
    # SPEC-Z-TRAINED CASE
    somtco_rs_test['TEST_Zrs'+str(i)] = umapz2.interpolator(df1=som_rs_spec, df2=somtco_rs_test, map='SOMrs'+str(i), dim=2, nn=75, calc='median', z_true='specz').copy()['TEST_Z']
    somtco_rs_test = somtco_rs_test.copy()[somtco_rs_test['lp_photoz']>z_cut]
    somtco_rs_test_i = somtco_rs_test.loc[somtco_rs_test['TEST_Zrs'+str(i)].copy().dropna().index.values]
    som_testcats_s.append(somtco_rs_test_i)
    missing_s_i = len(somtco_rs_test) - len(somtco_rs_test_i)

    ## UMAPz
    umap_rs_test['TEST_Zrs'+str(i)] = umapz2.interpolator(df1=umap_rs_spec, df2=umap_rs_test, map='UMAPrs'+str(i), dim=3, nn=15, calc='median', z_true='specz').copy()['TEST_Z']
    umap_rs_test = umap_rs_test.copy()[umap_rs_test['lp_photoz']>z_cut]
    # filter for galaxies in trained SOM cells only
    umap_rs_test_i = umap_rs_test.copy()[umap_rs_test['ID'].isin(somtco_rs_test_i['ID'])]
    umap_outliers_rs.append(umapz2.f_outlier(i_vals=umap_rs_test_i['TEST_Zrs'+str(i)], t_vals=umap_rs_test_i['lp_photoz'], missing=0, threshold=0.15))
    umap_nmads_rs.append(umapz2.calc_nmad(i_vals=umap_rs_test_i['TEST_Zrs'+str(i)], t_vals=umap_rs_test_i['lp_photoz']))
    umap_biases_rs.append(umapz2.calc_bias(i_vals=umap_rs_test_i['TEST_Zrs'+str(i)], t_vals=umap_rs_test_i['lp_photoz']))

    ## colorsz
    # filter for galaxies in trained SOM cells only
    colors_rs_test_i = colors_test_s.copy()[colors_test_s['ID'].isin(somtco_rs_test_i['ID'])]
    colors_outliers_rs.append(umapz2.f_outlier(i_vals=colors_rs_test_i['TEST_Z'], t_vals=colors_rs_test_i['lp_photoz'], missing=0, threshold=0.15))
    colors_nmads_rs.append(umapz2.calc_nmad(i_vals=colors_rs_test_i['TEST_Z'], t_vals=colors_rs_test_i['lp_photoz']))
    colors_biases_rs.append(umapz2.calc_bias(i_vals=colors_rs_test_i['TEST_Z'], t_vals=colors_rs_test_i['lp_photoz']))

    ## SOM f_out (OTHER STATS DON'T CHANGE FOR THIS TEST)
    somtco_outliers_rs.append(umapz2.f_outlier(i_vals=somtco_rs_test_i['TEST_Zrs'+str(i)], t_vals=somtco_rs_test_i['lp_photoz'], missing=missing_s_i, threshold=0.15))

    ###
    # LEPHARE-TRAINED CASE
    ###
    somtco_rs_test_lp['TEST_Zrs'+str(i)] = umapz2.interpolator(df1=som_rs_train_lp, df2=somtco_rs_test_lp, map='SOMrs'+str(i), dim=2, nn=75, calc='median', z_true='lp_photoz').copy()['TEST_Z']
    somtco_rs_test_lp = somtco_rs_test_lp.copy()[somtco_rs_test_lp['lp_photoz']>z_cut]
    somtco_rs_test_lp_i = somtco_rs_test_lp.loc[somtco_rs_test_lp['TEST_Zrs'+str(i)].copy().dropna().index.values]
    som_testcats_lp.append(somtco_rs_test_lp_i)
    missing_lp_i = len(somtco_rs_test_lp) - len(somtco_rs_test_lp_i)

    ## UMAPz
    umap_rs_test_lp['TEST_Zrs'+str(i)] = umapz2.interpolator(df1=umap_rs_train_lp, df2=umap_rs_test_lp, map='UMAPrs'+str(i), dim=3, nn=15, calc='median', z_true='lp_photoz').copy()['TEST_Z']
    umap_rs_test_lp = umap_rs_test_lp.copy()[umap_rs_test_lp['lp_photoz']>z_cut]
    # filter for galaxies in trained SOM cells only
    umap_rs_test_lp_i = umap_rs_test_lp.copy()[umap_rs_test_lp['ID'].isin(somtco_rs_test_lp_i['ID'])]
    umap_outliers_rs_lp.append(umapz2.f_outlier(i_vals=umap_rs_test_lp_i['TEST_Zrs'+str(i)], t_vals=umap_rs_test_lp_i['lp_photoz'], missing=0, threshold=0.15))
    umap_nmads_rs_lp.append(umapz2.calc_nmad(i_vals=umap_rs_test_lp_i['TEST_Zrs'+str(i)], t_vals=umap_rs_test_lp_i['lp_photoz']))
    umap_biases_rs_lp.append(umapz2.calc_bias(i_vals=umap_rs_test_lp_i['TEST_Zrs'+str(i)], t_vals=umap_rs_test_lp_i['lp_photoz']))
    
    ## colorsz
    # filter for galaxies in trained SOM cells only
    colors_rs_test_lp_i = colors_test_lp.copy()[colors_test_lp['ID'].isin(somtco_rs_test_lp_i['ID'])]
    colors_outliers_rs_lp.append(umapz2.f_outlier(i_vals=colors_rs_test_lp_i['TEST_Z'], t_vals=colors_rs_test_lp_i['lp_photoz'], missing=0, threshold=0.15))
    colors_nmads_rs_lp.append(umapz2.calc_nmad(i_vals=colors_rs_test_lp_i['TEST_Z'], t_vals=colors_rs_test_lp_i['lp_photoz']))
    colors_biases_rs_lp.append(umapz2.calc_bias(i_vals=colors_rs_test_lp_i['TEST_Z'], t_vals=colors_rs_test_lp_i['lp_photoz']))

    ## SOM f_out (OTHER STATS DON'T CHANGE FOR THIS TEST)
    somtco_outliers_rs_lp.append(umapz2.f_outlier(i_vals=somtco_rs_test_lp_i['TEST_Zrs'+str(i)], t_vals=somtco_rs_test_lp_i['lp_photoz'], missing=missing_lp_i, threshold=0.15))
    somtco_rs_test_i,somtco_rs_test_lp_i,missing_s_i,missing_lp_i,umap_rs_test_lp_i,umap_rs_test_i,colors_rs_test_lp_i,colors_rs_test_i = [],[],[],[],[],[],[],[]

In [1]:
print(len(som_testcats_s))
som_testcats_s[0]

NameError: name 'som_testcats_s' is not defined

In [16]:
#umap_outliers_rs = []
#umap_nmads_rs = []
#umap_biases_rs = []

#for i in range(n_embeddings):
#    som_tco_rs_test_i = som_testcats_s[i]
#    umap_rs_test['TEST_Zrs'+str(i)] = umapz2.interpolator(df1=umap_rs_spec, df2=umap_rs_test, map='UMAPrs'+str(i), dim=3, nn=15, calc='median', z_true='specz').copy()['TEST_Z']
#    umap_rs_test = umap_rs_test.copy()[umap_rs_test['lp_photoz']>z_cut]
#    # filter for galaxies in trained SOM cells only
#    umap_rs_test_i = umap_rs_test.copy()[umap_rs_test['ID'].isin(somtco_rs_test_i['ID'])]
#    umap_outliers_rs.append(umapz2.f_outlier(i_vals=umap_rs_test_i['TEST_Zrs'+str(i)], t_vals=umap_rs_test_i['lp_photoz'], missing=0, threshold=0.15))
#    umap_nmads_rs.append(umapz2.calc_nmad(i_vals=umap_rs_test_i['TEST_Zrs'+str(i)], t_vals=umap_rs_test_i['lp_photoz']))
#    umap_biases_rs.append(umapz2.calc_bias(i_vals=umap_rs_test_i['TEST_Zrs'+str(i)], t_vals=umap_rs_test_i['lp_photoz']))
#    som_tco_rs_test_i = []

In [17]:
# convert to arrays: shape = (n_realizations, n_bins)
somtco_outliers_rs = np.asarray(somtco_outliers_rs)
somtco_outliers_rs_lp = np.asarray(somtco_outliers_rs_lp)

somtco_rs_results = {
    "outliers_mean": somtco_outliers_rs.mean(axis=0),
    "outliers_std": somtco_outliers_rs.std(axis=0),
    "outliers_mean_lp": somtco_outliers_rs_lp.mean(axis=0),
    "outliers_std_lp": somtco_outliers_rs_lp.std(axis=0),
}

In [18]:
# convert to arrays: shape = (n_realizations, n_bins)
umap_outliers_rs = np.asarray(umap_outliers_rs)
umap_nmads_rs = np.asarray(umap_nmads_rs)
umap_biases_rs = np.asarray(umap_biases_rs)

umap_outliers_rs_lp = np.asarray(umap_outliers_rs_lp)
umap_nmads_rs_lp = np.asarray(umap_nmads_rs_lp)
umap_biases_rs_lp = np.asarray(umap_biases_rs_lp)

umap_rs_results = {
    "outliers_mean": umap_outliers_rs.mean(axis=0),
    "outliers_std": umap_outliers_rs.std(axis=0),

    "nmads_mean": umap_nmads_rs.mean(axis=0),
    "nmads_std": umap_nmads_rs.std(axis=0),

    "biases_mean": umap_biases_rs.mean(axis=0),
    "biases_std": umap_biases_rs.std(axis=0),

    "outliers_mean_lp": umap_outliers_rs_lp.mean(axis=0),
    "outliers_std_lp": umap_outliers_rs_lp.std(axis=0),

    "nmads_mean_lp": umap_nmads_rs_lp.mean(axis=0),
    "nmads_std_lp": umap_nmads_rs_lp.std(axis=0),

    "biases_mean_lp": umap_biases_rs_lp.mean(axis=0),
    "biases_std_lp": umap_biases_rs_lp.std(axis=0)
}

In [19]:
# convert to arrays: shape = (n_realizations, n_bins)
colors_outliers_rs = np.asarray(colors_outliers_rs)
colors_nmads_rs = np.asarray(colors_nmads_rs)
colors_biases_rs = np.asarray(colors_biases_rs)

colors_outliers_rs_lp = np.asarray(colors_outliers_rs_lp)
colors_nmads_rs_lp = np.asarray(colors_nmads_rs_lp)
colors_biases_rs_lp = np.asarray(colors_biases_rs_lp)

colors_rs_results = {
    "outliers_mean": colors_outliers_rs.mean(axis=0),
    "outliers_std": colors_outliers_rs.std(axis=0),

    "nmads_mean": colors_nmads_rs.mean(axis=0),
    "nmads_std": colors_nmads_rs.std(axis=0),

    "biases_mean": colors_biases_rs.mean(axis=0),
    "biases_std": colors_biases_rs.std(axis=0),

    "outliers_mean_lp": colors_outliers_rs_lp.mean(axis=0),
    "outliers_std_lp": colors_outliers_rs_lp.std(axis=0),

    "nmads_mean_lp": colors_nmads_rs_lp.mean(axis=0),
    "nmads_std_lp": colors_nmads_rs_lp.std(axis=0),

    "biases_mean_lp": colors_biases_rs_lp.mean(axis=0),
    "biases_std_lp": colors_biases_rs_lp.std(axis=0)
}

#### uncertainty due to finite test set

To quantify the uncertainty due to the finite test set, we take 10-25 bootstrap samples of the test set (spec-z-trained case) and perform the main redshift-binned interpolation test with fixed k, n_neighbors, and random seed. The standard deviation of the performance metrics in each bin will be taken as the uncertainty due to finite test size.

Since the random seed test we just performed used fixed n_neighbors and fixed k, if we pick a particular seed from which to use the interpolated redshifts, we can use this sample for our bootstrap performance statistics calculations.

Let's go with 3.

For colors-kNN-z, there is no comparable step to generating the SOM and UMAP embeddings with the associated random seed uncertainty. For this algorithm, we simply run it on the full test sets and use the results for the bootstrap uncertainty calculation below.

In [20]:
colors_test_s['TEST_Z'] = umapz2.interpolator_colors(df1=colors_train_s, df2=colors_test_s, coords=['u-g', 'g-r', 'r-i', 'i-z', 
                                    'z-y', 'y-J', 'J-H'], nn=11, calc='median', z_true='specz', p=1).copy()['TEST_Z']
colors_test_s = colors_test_s.copy()[colors_test_s['lp_photoz']>z_cut]
colors_test_lp['TEST_Z'] = umapz2.interpolator_colors(df1=colors_train_lp, df2=colors_test_lp, coords=['u-g', 'g-r', 'r-i', 'i-z', 
                                    'z-y', 'y-J', 'J-H'], nn=11, calc='median', z_true='lp_photoz', p=1).copy()['TEST_Z']
colors_test_lp = colors_test_lp.copy()[colors_test_lp['lp_photoz']>z_cut]

In [21]:
n_boots=25
rs=3
somtco_outliers_boots = []
somtco_testcats_boots = []
somtco_outliers_boots_lp = []
somtco_testcats_boots_lp = []

umap_outliers_boots = []
umap_nmads_boots = []
umap_stdevs_boots = []
umap_biases_boots = []
umap_testcats_boots = []
umap_outliers_boots_lp = []
umap_nmads_boots_lp = []
umap_stdevs_boots_lp = []
umap_biases_boots_lp = []
umap_testcats_boots_lp = []

colors_outliers_boots = []
colors_nmads_boots = []
colors_stdevs_boots = []
colors_biases_boots = []
colors_testcats_boots = []
colors_outliers_boots_lp = []
colors_nmads_boots_lp = []
colors_stdevs_boots_lp = []
colors_biases_boots_lp = []
colors_testcats_boots_lp = []

for i in range(1, n_boots+1):
    # SPEC-Z-TRAINED CASE
    somtco_rs_test = somtco_rs_test.copy()[somtco_rs_test['lp_photoz']>z_cut]
    somtco_rs_test_i = somtco_rs_test.copy().loc[somtco_rs_test['TEST_Zrs'+str(rs)].copy().dropna().index.values]
    missing_s_i = len(somtco_rs_test) - len(somtco_rs_test_i)
    umap_rs_test_i = umap_rs_test.copy()[umap_rs_test['ID'].isin(somtco_rs_test_i['ID'])]
    colors_rs_test_i = colors_test_s.copy()[colors_test_s['ID'].isin(somtco_rs_test_i['ID'])]

    somtco_boot_i = somtco_rs_test_i.sample(n=len(somtco_rs_test_i), replace=True, random_state=i)
    somtco_testcats_boots.append(somtco_boot_i.copy())
    somtco_outliers_boots.append(umapz2.f_outlier(i_vals=somtco_boot_i['TEST_Zrs'+str(rs)], t_vals=somtco_boot_i['lp_photoz'], 
                                           missing=missing_s_i, threshold=0.15))

    # umapz
    umap_boot_i = umap_rs_test_i.sample(n=len(umap_rs_test_i), replace=True, random_state=i)
    umap_testcats_boots.append(umap_boot_i.copy())
    umap_outliers_boots.append(umapz2.f_outlier(i_vals=umap_boot_i['TEST_Zrs'+str(rs)], t_vals=umap_boot_i['lp_photoz'], 
                                           missing=0, threshold=0.15))
    umap_nmads_boots.append(umapz2.calc_nmad(i_vals=umap_boot_i['TEST_Zrs'+str(rs)], t_vals=umap_boot_i['lp_photoz']))
    umap_stdevs_boots.append(umapz2.calc_stdev(i_vals=umap_boot_i['TEST_Zrs'+str(rs)], t_vals=umap_boot_i['lp_photoz']))
    umap_biases_boots.append(umapz2.calc_bias(i_vals=umap_boot_i['TEST_Zrs'+str(rs)], t_vals=umap_boot_i['lp_photoz']))

    #colorsz
    colors_boot_i = colors_rs_test_i.sample(n=len(colors_rs_test_i), replace=True, random_state=i)
    colors_testcats_boots.append(colors_boot_i.copy())
    colors_outliers_boots.append(umapz2.f_outlier(i_vals=colors_boot_i['TEST_Z'], t_vals=colors_boot_i['lp_photoz'], 
                                           missing=0, threshold=0.15))
    colors_nmads_boots.append(umapz2.calc_nmad(i_vals=colors_boot_i['TEST_Z'], t_vals=colors_boot_i['lp_photoz']))
    colors_stdevs_boots.append(umapz2.calc_stdev(i_vals=colors_boot_i['TEST_Z'], t_vals=colors_boot_i['lp_photoz']))
    colors_biases_boots.append(umapz2.calc_bias(i_vals=colors_boot_i['TEST_Z'], t_vals=colors_boot_i['lp_photoz']))


    # LEPHARE-TRAINED CASE
    somtco_rs_test_lp = somtco_rs_test_lp.copy()[somtco_rs_test_lp['lp_photoz']>z_cut]
    somtco_rs_test_i_lp = somtco_rs_test_lp.copy().loc[somtco_rs_test_lp['TEST_Zrs'+str(rs)].copy().dropna().index.values]
    missing_lp_i = len(somtco_rs_test_lp) - len(somtco_rs_test_i_lp)
    umap_rs_test_lp_i = umap_rs_test_lp.copy()[umap_rs_test_lp['ID'].isin(somtco_rs_test_i_lp['ID'])]
    colors_rs_test_lp_i = colors_test_lp.copy()[colors_test_lp['ID'].isin(somtco_rs_test_i_lp['ID'])]

    somtco_boot_i_lp = somtco_rs_test_i_lp.sample(n=len(somtco_rs_test_i_lp), replace=True, random_state=i)
    somtco_testcats_boots_lp.append(somtco_boot_i_lp.copy())
    somtco_outliers_boots_lp.append(umapz2.f_outlier(i_vals=somtco_boot_i_lp['TEST_Zrs'+str(rs)], t_vals=somtco_boot_i_lp['lp_photoz'], 
                                           missing=missing_lp_i, threshold=0.15))

    # umapz
    umap_boot_i_lp = umap_rs_test_lp_i.sample(n=len(umap_rs_test_lp_i), replace=True, random_state=i)
    umap_testcats_boots_lp.append(umap_boot_i_lp.copy())
    umap_outliers_boots_lp.append(umapz2.f_outlier(i_vals=umap_boot_i_lp['TEST_Zrs'+str(rs)], t_vals=umap_boot_i_lp['lp_photoz'], 
                                           missing=0, threshold=0.15))
    umap_nmads_boots_lp.append(umapz2.calc_nmad(i_vals=umap_boot_i_lp['TEST_Zrs'+str(rs)], t_vals=umap_boot_i_lp['lp_photoz']))
    umap_stdevs_boots_lp.append(umapz2.calc_stdev(i_vals=umap_boot_i_lp['TEST_Zrs'+str(rs)], t_vals=umap_boot_i_lp['lp_photoz']))
    umap_biases_boots_lp.append(umapz2.calc_bias(i_vals=umap_boot_i_lp['TEST_Zrs'+str(rs)], t_vals=umap_boot_i_lp['lp_photoz']))

    # colorsz
    colors_boot_i_lp = colors_rs_test_lp_i.sample(n=len(colors_rs_test_lp_i), replace=True, random_state=i)
    colors_testcats_boots_lp.append(colors_boot_i_lp.copy())
    colors_outliers_boots_lp.append(umapz2.f_outlier(i_vals=colors_boot_i_lp['TEST_Z'], t_vals=colors_boot_i_lp['lp_photoz'], 
                                           missing=0, threshold=0.15))
    colors_nmads_boots_lp.append(umapz2.calc_nmad(i_vals=colors_boot_i_lp['TEST_Z'], t_vals=colors_boot_i_lp['lp_photoz']))
    colors_stdevs_boots_lp.append(umapz2.calc_stdev(i_vals=colors_boot_i_lp['TEST_Z'], t_vals=colors_boot_i_lp['lp_photoz']))
    colors_biases_boots_lp.append(umapz2.calc_bias(i_vals=colors_boot_i_lp['TEST_Z'], t_vals=colors_boot_i_lp['lp_photoz']))

In [22]:
# convert to arrays: shape = (n_realizations, n_bins)
# trained-cells-only
somtco_outliers_boots = np.asarray(somtco_outliers_boots)
somtco_outliers_boots_lp = np.asarray(somtco_outliers_boots_lp)

somtco_boots_results = {
    "outliers_mean": somtco_outliers_boots.mean(axis=0),
    "outliers_std": somtco_outliers_boots.std(axis=0),
    "outliers_mean_lp": somtco_outliers_boots_lp.mean(axis=0),
    "outliers_std_lp": somtco_outliers_boots_lp.std(axis=0)
}

In [23]:
# convert to arrays: shape = (n_realizations, n_bins)
colors_outliers_boots = np.asarray(colors_outliers_boots)
colors_nmads_boots = np.asarray(colors_nmads_boots)
colors_stdevs_boots = np.asarray(colors_stdevs_boots)
colors_biases_boots = np.asarray(colors_biases_boots)

colors_outliers_boots_lp = np.asarray(colors_outliers_boots_lp)
colors_nmads_boots_lp = np.asarray(colors_nmads_boots_lp)
colors_stdevs_boots_lp = np.asarray(colors_stdevs_boots_lp)
colors_biases_boots_lp = np.asarray(colors_biases_boots_lp)

colors_boots_results = {
    "outliers_mean": colors_outliers_boots.mean(axis=0),
    "outliers_std": colors_outliers_boots.std(axis=0),

    "nmads_mean": colors_nmads_boots.mean(axis=0),
    "nmads_std": colors_nmads_boots.std(axis=0),

    "stdevs_mean": colors_stdevs_boots.mean(axis=0),
    "stdevs_std": colors_stdevs_boots.std(axis=0),

    "biases_mean": colors_biases_boots.mean(axis=0),
    "biases_std": colors_biases_boots.std(axis=0),

    "outliers_mean_lp": colors_outliers_boots_lp.mean(axis=0),
    "outliers_std_lp": colors_outliers_boots_lp.std(axis=0),

    "nmads_mean_lp": colors_nmads_boots_lp.mean(axis=0),
    "nmads_std_lp": colors_nmads_boots_lp.std(axis=0),

    "stdevs_mean_lp": colors_stdevs_boots_lp.mean(axis=0),
    "stdevs_std_lp": colors_stdevs_boots_lp.std(axis=0),

    "biases_mean_lp": colors_biases_boots_lp.mean(axis=0),
    "biases_std_lp": colors_biases_boots_lp.std(axis=0)
}

In [24]:
# convert to arrays: shape = (n_realizations, n_bins)
umap_outliers_boots = np.asarray(umap_outliers_boots)
umap_nmads_boots = np.asarray(umap_nmads_boots)
umap_stdevs_boots = np.asarray(umap_stdevs_boots)
umap_biases_boots = np.asarray(umap_biases_boots)

umap_outliers_boots_lp = np.asarray(umap_outliers_boots_lp)
umap_nmads_boots_lp = np.asarray(umap_nmads_boots_lp)
umap_stdevs_boots_lp = np.asarray(umap_stdevs_boots_lp)
umap_biases_boots_lp = np.asarray(umap_biases_boots_lp)

umap_boots_results = {
    "outliers_mean": umap_outliers_boots.mean(axis=0),
    "outliers_std": umap_outliers_boots.std(axis=0),

    "nmads_mean": umap_nmads_boots.mean(axis=0),
    "nmads_std": umap_nmads_boots.std(axis=0),

    "stdevs_mean": umap_stdevs_boots.mean(axis=0),
    "stdevs_std": umap_stdevs_boots.std(axis=0),

    "biases_mean": umap_biases_boots.mean(axis=0),
    "biases_std": umap_biases_boots.std(axis=0),

    "outliers_mean_lp": umap_outliers_boots_lp.mean(axis=0),
    "outliers_std_lp": umap_outliers_boots_lp.std(axis=0),

    "nmads_mean_lp": umap_nmads_boots_lp.mean(axis=0),
    "nmads_std_lp": umap_nmads_boots_lp.std(axis=0),

    "stdevs_mean_lp": umap_stdevs_boots_lp.mean(axis=0),
    "stdevs_std_lp": umap_stdevs_boots_lp.std(axis=0),

    "biases_mean_lp": umap_biases_boots_lp.mean(axis=0),
    "biases_std_lp": umap_biases_boots_lp.std(axis=0)
}

### Global Performance Metric Uncertainties

This section will compute the uncertainties on the full-sample performance statistics. The same approach will be used, taking the range of means divided by 2 for the uncertainties associated with our embedding choices (size, sigma, learning_rate), using 5-fold crossvalidation tests on the validation sample, and taking the standard deviation of the performance metrics obtained over 25 trials for the uncertainties associated with embedding random seed (25 seeds, spec-z train/test sets) and the finite test set (25 bootstraps of the (spec-z) test sample for one random seed run).

In [25]:
# valid contains the cell coordinates for the validation dataset for various embedding choice combinations, 
# all using the same random seed (42)
# this data is used to calculate the +/-15% uncertainties associated with choice of these
# parameters
valid

,ID,RA,DEC,FLAG_COMBINED,CFHT_u_FLUX,CFHT_u_FLUXERR,CFHT_u_MAGERR,HSC_g_FLUX,HSC_g_FLUXERR,HSC_g_MAGERR,HSC_r_FLUX,HSC_r_FLUXERR,HSC_r_MAGERR,HSC_i_FLUX,HSC_i_FLUXERR,HSC_i_MAGERR,HSC_z_FLUX,HSC_z_FLUXERR,HSC_z_MAGERR,HSC_y_FLUX,HSC_y_FLUXERR,HSC_y_MAGERR,UVISTA_J_FLUX,UVISTA_J_FLUXERR,UVISTA_J_MAGERR,UVISTA_H_FLUX,UVISTA_H_FLUXERR,UVISTA_H_MAGERR,UVISTA_Ks_FLUX,UVISTA_Ks_FLUXERR,UVISTA_Ks_MAGERR,IRAC_CH1_FLUX,IRAC_CH1_FLUXERR,IRAC_CH1_MAGERR,IRAC_CH2_FLUX,IRAC_CH2_FLUXERR,IRAC_CH2_MAGERR,lp_photoz,lp_type,lp_zp_2,lp_NbFilt,lp_zq,lp_model,lp_age,lp_dust,lp_Attenuation,lp_MNUV,lp_MR,lp_MJ,lp_mass_med,lp_mass_med_min68,lp_mass_med_max68,lp_mass_best,lp_SFR_med,lp_sSFR_best,CFHT_u_MAG,HSC_g_MAG,HSC_r_MAG,HSC_i_MAG,HSC_z_MAG,HSC_y_MAG,UVISTA_J_MAG,UVISTA_H_MAG,UVISTA_Ks_MAG,IRAC_CH1_MAG,IRAC_CH2_MAG,u-g,g-r,r-i,i-z,z-y,y-J,J-H,SOM_46_92_s0.85_lr0.68-1,SOM_46_92_s0.85_lr0.68-2,SOM_46_92_s0.85_lr0.8-1,SOM_46_92_s0.85_lr0.8-2,SOM_46_92_s0.85_lr0.92-1,SOM_46_92_s0.85_lr0.92-2,SOM_46_92_s1_lr0.68-1,SOM_46_92_s1_lr0.68-2,SOM_46_92_s1_lr0.8-1,SOM_46_92_s1_lr0.8-2,SOM_46_92_s1_lr0.92-1,SOM_46_92_s1_lr0.92-2,SOM_46_92_s1.15_lr0.68-1,SOM_46_92_s1.15_lr0.68-2,SOM_46_92_s1.15_lr0.8-1,SOM_46_92_s1.15_lr0.8-2,SOM_46_92_s1.15_lr0.92-1,SOM_46_92_s1.15_lr0.92-2,SOM_50_100_s0.85_lr0.68-1,SOM_50_100_s0.85_lr0.68-2,SOM_50_100_s0.85_lr0.8-1,SOM_50_100_s0.85_lr0.8-2,SOM_50_100_s0.85_lr0.92-1,SOM_50_100_s0.85_lr0.92-2,SOM_50_100_s1_lr0.68-1,SOM_50_100_s1_lr0.68-2,SOM_50_100_s1_lr0.8-1,SOM_50_100_s1_lr0.8-2,SOM_50_100_s1_lr0.92-1,SOM_50_100_s1_lr0.92-2,SOM_50_100_s1.15_lr0.68-1,SOM_50_100_s1.15_lr0.68-2,SOM_50_100_s1.15_lr0.8-1,SOM_50_100_s1.15_lr0.8-2,SOM_50_100_s1.15_lr0.92-1,SOM_50_100_s1.15_lr0.92-2,SOM_54_108_s0.85_lr0.68-1,SOM_54_108_s0.85_lr0.68-2,SOM_54_108_s0.85_lr0.8-1,SOM_54_108_s0.85_lr0.8-2,SOM_54_108_s0.85_lr0.92-1,SOM_54_108_s0.85_lr0.92-2,SOM_54_108_s1_lr0.68-1,SOM_54_108_s1_lr0.68-2,SOM_54_108_s1_lr0.8-1,SOM_54_108_s1_lr0.8-2,SOM_54_108_s1_lr0.92-1,SOM_54_108_s1_lr0.92-2,SOM_54_108_s1.15_lr0.68-1,SOM_54_108_s1.15_lr0.68-2,SOM_54_108_s1.15_lr0.8-1,SOM_54_108_s1.15_lr0.8-2,SOM_54_108_s1.15_lr0.92-1,SOM_54_108_s1.15_lr0.92-2
682744,888967,149.936450,2.785401,0,0.482169,0.008109,0.021217,0.556797,0.004353,0.008433,0.649724,0.005866,0.009340,0.815287,0.006075,0.008074,1.022175,0.009601,0.010115,1.516981,0.023160,0.015645,2.479349,0.054714,0.023929,3.181551,0.075771,0.027204,3.775385,0.057224,0.016556,5.577980,0.014766,0.003503,6.055261,0.017200,0.003780,1.5429,0,NaN,27,0.99,5,1.139000e+09,0.2,0,-19.84784,-21.53190,-22.12276,10.02579,9.89337,10.08403,10.03590,1.14004,-8.917,24.692001,24.535758,24.368177,24.121724,23.876187,23.447549,22.914156,22.643403,22.457597,22.033808,21.944668,0.156243,0.167580,0.246453,0.245537,0.428638,0.533394,0.270753,33,16,18,34,23,41,29,23,7,73,25,31,33,34,26,42,39,13,24,88,21,91,31,11,35,87,21,94,14,85,17,94,44,86,10,88,18,93,15,93,35,103,40,100,17,103,36,106,25,99,39,104,28,100
705718,915989,150.389923,1.791782,0,0.300923,0.003346,0.013912,0.391560,0.003238,0.008863,0.729946,0.004244,0.005987,0.857738,0.004264,0.005368,0.908493,0.006994,0.008269,1.053736,0.015095,0.014646,1.133205,0.028540,0.027268,1.063807,0.038095,0.040864,1.151679,0.027239,0.025818,0.553292,0.012940,0.030942,0.312715,0.016622,0.070726,0.4445,0,NaN,30,0.00,1,3.210000e+08,0.0,0,-16.35030,-17.63879,-17.70557,8.08427,8.02849,8.19774,8.06536,-1.17000,-9.212,25.203863,24.918003,24.241773,24.066614,24.004195,23.843171,23.764228,23.832843,23.746671,24.542615,25.162128,0.285860,0.676230,0.175160,0.062418,0.161025,0.078942,-0.068615,7,89,6,22,7,29,22,54,2,36,12,39,16,83,11,81,10,90,12,51,30,70,2,45,12,49,7,56,40,71,46,52,36,79,43,69,37,105,2,17,40,49,2,0,5,15,5,22,45,34,6,16,4,19
132564,175014,150.121155,1.644934,0,0.281661,0.003567,0.015858,0.294709,0.003148,0.011457,0.385362,0.004180,0.011174,0.606247,0.004185,0.007456,0.866615,0.006661,0.008258,0.800703,0.015264,0.019495,0.987316,0.013438,0.014739,0.996477,0.017941,0.020548,0.986751,0.026845,0.029699,0.839995,0.013123,0.020670,0.550881,0.013868,0.033498,0.8564,0,NaN,29,0.00,7,1.015000e+09,0.1,1,-17.75778,-18.94959,-19.07940,8.71424,8.66864,8.75055,8.73949,-0.09519,-8.830,25.275684,25.226517,24.935328,24.443377,24.055434,24.141322,23.913860,23.903831,23.914481,24.089309,24.547356,0.049166,0.291189,0.491951,0.387943,-0.085888,0.227462,0.010028,13,49,6,56,17,51,12,48,15,58,17,54,18,41,3,64,16,81,22,18,42,87,19,26,13,16,14,24,12,24,20,31,49,5,43,5,40,34,24,35,5,31,47,84,15,7,23,85,12,101,49,100,26,7
38676,53915,150.365002,2.127347,0,0.467036,0.006094,0.016220,0.526304,0.004793,0.009714,0.840886,0.006087,0.007426,1.706182,0.006378,0.004026,2.390468,0.010503,0.004710,2.376359,0.021343,0.009167,3.818460,0.042345,0.011993,4.366636,0.056518,0.014759,5.914739,0.041212,0.007602,7.887154,0.016861,0.002828,6.016602,0.020844,0.004609,0.8240,0,NaN,29,0.74,3,5.709000e+08,0.3,0,-18.17301,-20.26624,-20.98757,9.55956,9.51840,9.59472,9.53026,0.81388,-8.720,24.726624,24.596909,24.088157,23.319937,22.953793,22.960220,22.445280,22.299632,21.970161,21.657699,21.951622,0.129714,0.508752,0.768220,0.366144,-0.006427,0.514941,0.145647,25,55,10,46,45,50,39,18,45,63,33,1,17,9,27,52,32,21,32,81,7,13,41,39,6,2,2,3,27,25,23,35,38,21,15,35,47,85,34,69,38,37,50,67,48,84,22,38,18,105,52,79,45,42
739250,954912,149.888388,2.290574,0,0.826631,0.005465,0.008313,1.289190,0.004453,0.003717,2.720754,0.005884,0.002233,5.181314,0.006121,0.001278,6.401118,0.009896,0.001663,7.309192,0.020159,0.002824,9.951759,0.058052,0.006322,13.869990,0.071990,0.005926,19.369627,0.040532,0.002285,21.725130,0.017028,0.001037,15.774899,0.016255,0.001371,0.7021,0,NaN,29,0.67,7,5.088000e+08,0.5,1,-18.45950,-20.96760,-21.87276,9.88231,9.84503,9.92537,9.84081,1.30000,-8.550,24.106721,23.624208,22.813277,22.113900,21.884360,21.740327,21.405250,21.044810,20.682197,20.557594,20.905084,0.482513,0.810931,0.699377,0.229540,0.144034,0.335076,0.360441,2,3,26,7,3,10,33,52,35,21,23,70,25,52,28,69,27,81,21,34,44,21,20,79,33,58,7,11,40,82,32,63,27,51,27,81,33,83,1,71,45,82,1,82,45,76,10,75,40,78,38,43,27,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
684584,891138,150.110471,1.777353,0,0.296048,0.005221,0.021937,0.312364,0.003521,0.012030,0.508558,0.004627,0.009337,0.829878,0.004729,0.006138,1.036933,0.007572,0.007828,1.030603,0.016646,0.016488,1.247287,0.012057,0.010455,1.467359,0.016032,0.012459,1.553659,0.023101,0.016223,1.349267,0.009179,0.008999,0.898451,0.010706,0.015853,0.7395,0,NaN,29,0.00,7,1.015000e+09,0.2,1,-17.33409,-18.99425,-19.25434,8.82421,8.78011,8.86880,8.85254,0.00044,-8.830,25.221593,25.163349,24.634149,24.102465,23.860623,23.867272,23.660084,23.483659,23.421611,23.574755,24.016264,0.058244,0.529201,0.531684,0.241842,-0.006649,0.207188,0.176425,18,81,40,11,26,57,15,81,28,81,37,6,12,16,15,62,20,76,15,17,43,81,40,32,5,7,13,22,11,30,11,46,46,14,43,93,37,41,21,29,4,76,43,79,35,9,16,84,32,34,18,33,44,97
427923,571071,150.772739,1.921325,0,0.724656,0.005547,0.009648,0.917149,0.004717,0.005544,1.590404,0.006477,0.004211,3.466228,0.006843,0.002138,5.315191,0.011298,0.002288,6.166483,0.024737,0.004110,8.671765,0.054305,0.006790,12.070129,0.071572,0.006772,16.333579,0.045231,0.003025,22.720054,0.022136,0.001289,17.737899,0.026435,0.001983,0.9833,0,NaN,29,0.94,9,2.300000e+09,0.3,1,-19.22390,-21.64550,-22.48912,10.30044,10.26566,10.33554,10.29149,1.10086,-9.248,24.249670,23.993900,23.396231,22.550357,22.086203,21.924906,21.554731,21.195720,20.867297,20.508977,20.777745,0.255770,0.597669,0.845874,0.464154,0.161297,0.370175,0.359011,26,53,44,46,28,77,37,49,35,72,30,55,20,5,30,49,41,45,38,82,10,14,15,13,16,3,9,3,45,23,1,71,48,22,27,86,49,57,45,88,41,86,44,64,53,76,48,71,43,80,8,90,28,41
599855,790913,150.055650,2.681121,0,0.222790,0.007355,0.041457,0.232116,0.004918,0.022777,0.450094,0.006607,0.015146,0.993257,0.006998,0.007619,1.775239,0.011250,0.006814,2.260605,0.024694,0.011180,3.981098,0.014831,0.004036,6.266626,0.019997,0.003643,9.861777,0.031682,0.003508,16.374265,0.033513,0.002708,14.218412,0.029937,0.002802,1.0852,0,NaN,29,1.04,10,1.609000e+09,0.5,0,-18.02475,-21.23968,-22.28055,10.24881,10.19431,10.33383,10.23888,1.35714,-8.800,25.530263,25.485736,24.766743,23.907346,23.276858,23.014438,22.399993,21.907416,21.415112,20.864595,21.017872,0.044527,0.718994,0.859397,0.630487,0.262420,0.614445,0.492577,44,51,35,44,29,76,38,0,35,89,28,5,36,5,31,1,44,46,40,24,29,2,49,43,42,25,11,0,34,27,31,93,33,35,37,30,53,79,33,86,16,40,35,52,47,48,33,82,53,70,33,84,50,73
104,187,150.727327,1.794051,0,1.077269,0.004572,0.005362,1.322689,0.004821,0.003937,1.380330,0.006299,0.004726,1.514137,0.006054,0.004335,1.726628,0.009914,0.006186,2.687333,0.021823,0.008325,2.992035,0.053495,0.019393,3.628191,0.059291,0.018670,3.787613,0.034818,0.010042,4.799319,0.018039,0.004974,5.398208,0.023180,0.005715,1.5271,0,NaN,28,2.35,12,1.805000e+08,0.2,0,-20.65049,-21.56226,-21.92586,9.43635,9.40054,9.48063,9.45094,1.59673,-7.857,23.819190,23.596356,23.550043,23.449587,23.307003,22.826696,22.710083,22.500775,22.454086,22.197051,22.069376,0.222834,0.046313,0.100456,0.142584,0.480307,0.116613,0.209309,14,32,20,38,19,42,19,24,28,30,30,30,18,30,43,19,44,12,48,64,21,90,31,16,25,83,18,97,30,90,13,95,44,91,12,93,13,0,11,93,25,105,41,107,36,102,31,104,37,106,33,106,31,102
542415,720423,150.463695,1.769475,0,0.534084,0.003426,0.008043,0.571298,0.003826,0.007190,0.695724,0.004837,0.007168,1.286778,0.005075,0.004263,1.629097,0.008167,0.005388,1.747869,0.018093,0.010590,2.216999,0.012493,0.006103,2.293473,0.016460,0.008192,2.446169,0.023374,0.010432,2.563994,0.015923,0.008217,2.031265,0.018048,0.011823,0.9002,0,NaN,30,0.00,5,4.535000e+08,0.2,0,-18.56275,-19.88653,-20.19196,9.17963,9.13639,9.22567,9.13358,0.60714,-8.520,24.580977,24.507844,24.293907,23.626241,23.370133,23.293728,23.035586,22.998766,22.928784,22.877707,23.130584,0.073133,0.213937,0.667666,0.256108,0.076405,0.258142,0.036820,23,29,43,17,18,78,6,50,37,57,20,44,15,42,13,52,33,27,47,89,43,6,40,29,44,10,45,83,44,1,42,39,31,15,22,22,4,34,43,37,22,30,52,50,33,13,47,40,25,26,3,97,27,18

In [26]:
# rs_data contains the cell coordinates for the full sample in 25 different random seed runs using the "best"
# embedding choices [size, sigma, learning_rate]
# this is used to calculate the uncertainties associated with the embedding random seed and with
# the finite test set size
umap_rs_data

,ID,RA,DEC,FLAG_COMBINED,CFHT_u_FLUX,CFHT_u_FLUXERR,CFHT_u_MAGERR,HSC_g_FLUX,HSC_g_FLUXERR,HSC_g_MAGERR,HSC_r_FLUX,HSC_r_FLUXERR,HSC_r_MAGERR,HSC_i_FLUX,HSC_i_FLUXERR,HSC_i_MAGERR,HSC_z_FLUX,HSC_z_FLUXERR,HSC_z_MAGERR,HSC_y_FLUX,HSC_y_FLUXERR,HSC_y_MAGERR,UVISTA_J_FLUX,UVISTA_J_FLUXERR,UVISTA_J_MAGERR,UVISTA_H_FLUX,UVISTA_H_FLUXERR,UVISTA_H_MAGERR,UVISTA_Ks_FLUX,UVISTA_Ks_FLUXERR,UVISTA_Ks_MAGERR,IRAC_CH1_FLUX,IRAC_CH1_FLUXERR,IRAC_CH1_MAGERR,IRAC_CH2_FLUX,IRAC_CH2_FLUXERR,IRAC_CH2_MAGERR,lp_photoz,lp_type,lp_zp_2,lp_NbFilt,lp_zq,lp_model,lp_age,lp_dust,lp_Attenuation,lp_MNUV,lp_MR,lp_MJ,lp_mass_med,lp_mass_med_min68,lp_mass_med_max68,lp_mass_best,lp_SFR_med,lp_sSFR_best,CFHT_u_MAG,HSC_g_MAG,HSC_r_MAG,HSC_i_MAG,HSC_z_MAG,HSC_y_MAG,UVISTA_J_MAG,UVISTA_H_MAG,UVISTA_Ks_MAG,IRAC_CH1_MAG,IRAC_CH2_MAG,u-g,g-r,r-i,i-z,z-y,y-J,J-H,UMAPrs0-1,UMAPrs0-2,UMAPrs0-3,UMAPrs1-1,UMAPrs1-2,UMAPrs1-3,UMAPrs2-1,UMAPrs2-2,UMAPrs2-3,UMAPrs3-1,UMAPrs3-2,UMAPrs3-3,UMAPrs4-1,UMAPrs4-2,UMAPrs4-3,UMAPrs5-1,UMAPrs5-2,UMAPrs5-3,UMAPrs6-1,UMAPrs6-2,UMAPrs6-3,UMAPrs7-1,UMAPrs7-2,UMAPrs7-3,UMAPrs8-1,UMAPrs8-2,UMAPrs8-3,UMAPrs9-1,UMAPrs9-2,UMAPrs9-3,UMAPrs10-1,UMAPrs10-2,UMAPrs10-3,UMAPrs11-1,UMAPrs11-2,UMAPrs11-3,UMAPrs12-1,UMAPrs12-2,UMAPrs12-3,UMAPrs13-1,UMAPrs13-2,UMAPrs13-3,UMAPrs14-1,UMAPrs14-2,UMAPrs14-3,UMAPrs15-1,UMAPrs15-2,UMAPrs15-3,UMAPrs16-1,UMAPrs16-2,UMAPrs16-3,UMAPrs17-1,UMAPrs17-2,UMAPrs17-3,UMAPrs18-1,UMAPrs18-2,UMAPrs18-3,UMAPrs19-1,UMAPrs19-2,UMAPrs19-3,UMAPrs20-1,UMAPrs20-2,UMAPrs20-3,UMAPrs21-1,UMAPrs21-2,UMAPrs21-3,UMAPrs22-1,UMAPrs22-2,UMAPrs22-3,UMAPrs23-1,UMAPrs23-2,UMAPrs23-3,UMAPrs24-1,UMAPrs24-2,UMAPrs24-3
7,12,150.476809,2.331511,0,0.432424,0.006043,0.017385,0.367684,0.004799,0.013929,0.539085,0.006673,0.012705,0.913139,0.006940,0.008187,0.995689,0.010382,0.011179,1.010389,0.021430,0.021652,1.176385,0.018240,0.016771,1.238664,0.023098,0.021265,1.273614,0.031158,0.026693,0.793401,0.012663,0.021113,0.623383,0.011264,0.024039,0.7070,0,NaN,30,0.00,5,9.048000e+08,0.1,1,-17.59872,-18.85507,-18.93651,8.69380,8.65194,8.74706,8.64422,-0.18369,-8.815,24.810225,24.986313,24.570856,23.998658,23.904690,23.888779,23.723626,23.667616,23.637405,24.151268,24.413112,-0.176089,0.415457,0.572198,0.093968,0.015911,0.165153,0.056011,-0.709033,3.736336,-1.030642,-0.757724,3.715452,-0.960332,-0.729527,3.673560,-0.973878,-0.701481,3.700125,-0.999021,-0.753197,3.725299,-0.992474,-0.771156,3.748387,-0.982547,-0.784931,3.740538,-0.950873,-0.689774,3.717718,-0.998636,-0.769059,3.781789,-1.019550,-0.800633,3.760602,-0.927774,-0.721482,3.773623,-0.979525,-0.706627,3.718313,-1.014884,-0.729159,3.752770,-0.988801,-0.753842,3.642118,-1.013089,-0.721901,3.850997,-1.034011,-0.786315,3.730866,-1.022281,-0.761800,3.646086,-0.999080,-0.764077,3.754936,-0.990492,-0.766461,3.694680,-1.029614,-0.763874,3.762229,-0.960837,-0.715766,3.653858,-0.998836,-0.773529,3.768091,-0.973538,-0.737911,3.724737,-0.949932,-0.750555,3.739782,-0.950880,-0.666117,3.713856,-1.064058
39,73,149.468025,1.625609,0,1.057806,0.006321,0.007477,1.301316,0.007003,0.005769,2.870638,0.011023,0.003954,3.669017,0.012785,0.003763,4.321371,0.018494,0.004597,5.147967,0.045866,0.009110,5.366495,0.022263,0.004492,5.903986,0.031370,0.006063,6.666023,0.046399,0.007598,4.142945,0.036884,0.011779,4.426406,0.054762,0.016462,0.4290,0,NaN,30,0.34,9,1.609000e+09,0.2,1,-17.40718,-19.16920,-19.50800,9.06086,9.01925,9.10800,9.01447,0.08064,-8.977,23.838985,23.614043,22.755054,22.488626,22.310946,22.120911,22.075773,21.972137,21.840333,22.356727,22.284872,0.224942,0.858989,0.266428,0.177680,0.190035,0.045137,0.103637,0.989098,6.007060,-1.049714,0.987686,5.938721,-0.990362,0.962178,5.943000,-0.987622,1.003128,5.988465,-1.037236,1.012951,5.951755,-0.999600,0.945584,5.987728,-0.969937,0.981110,5.998915,-0.965576,1.021070,5.980014,-1.018328,0.961282,6.010875,-1.032720,0.940405,6.025455,-0.962567,0.978602,6.019913,-0.968853,0.995895,5.984908,-1.070054,0.979596,5.990642,-0.996625,0.953561,5.937233,-1.055305,0.979251,6.075240,-1.016210,0.963120,5.999331,-1.010157,0.925422,5.890855,-1.031418,0.947024,6.031376,-1.016856,0.910755,5.990699,-1.017323,0.949258,6.022229,-0.987136,0.979702,5.927516,-1.019288,0.952963,6.034386,-0.991809,0.947504,5.988689,-0.953896,0.971227,5.996018,-0.992388,1.013451,5.970438,-1.068393
40,74,150.488035,1.875422,0,0.941051,0.003713,0.004937,1.032136,0.004159,0.004320,1.066959,0.005443,0.005254,1.123350,0.005748,0.005525,1.208387,0.008979,0.007981,1.734654,0.019518,0.011504,2.413042,0.014805,0.006643,2.547439,0.017875,0.008007,2.257407,0.024673,0.011931,2.951406,0.013003,0.005829,3.054308,0.014661,0.006387,1.5087,0,NaN,29,2.23,10,9.048000e+08,0.1,1,-20.37010,-21.24365,-21.42674,9.49598,9.44923,9.54398,9.50023,0.99993,-8.536,23.965967,23.865658,23.829631,23.773713,23.694485,23.301968,22.943588,22.884741,23.015975,22.724928,22.687718,0.100310,0.036027,0.055918,0.079228,0.392517,0.358380,0.058847,0.638806,4.104063,10.209574,0.549493,4.158031,10.217643,0.646084,4.177092,10.220542,0.643161,4.150405,10.226095,0.539548,4.119714,10.252411,0.608055,4.133068,10.262534,0.700793,4.089608,10.266313,0.644898,4.139221,10.225484,0.628430,4.074651,10.188632,0.669959,4.072044,10.232728,0.635200,4.071737,10.200725,0.595711,4.123669,10.208035,0.578698,4.086895,10.259074,0.599483,4.044958,10.237933,0.600465,4.080838,10.150708,0.653505,4.069032,10.263250,0.589795,4.073498,10.216737,0.685157,4.121945,10.200084,0.621520,4.093146,10.226449,0.584452,4.117673,10.238711,0.559216,4.150379,10.224091,0.651088,4.159864,10.245554,0.639164,4.198052,10.279202,0.656491,4.086607,10.239762,0.591389,4.161772,10.203028
46,85,150.476436,2.334178,0,0.685237,0.005227,0.009492,0.669388,0.004202,0.006701,0.744438,0.005884,0.008114,1.119968,0.005803,0.005582,1.484551,0.008772,0.006335,1.619744,0.018884,0.011903,1.782537,0.015855,0.009621,1.867551,0.020190,0.012329,2.274360,0.027033,0.012969,2.573668,0.012908,0.006634,1.992754,0.011691,0.007805,1.0800,0,NaN,29,2.19,5,2.273000e+08,0.2,0,-19.16843,-20.47925,-20.51206,9.14079,9.10236,9.18581,9.12799,0.90000,-8.234,24.310399,24.335805,24.220428,23.776986,23.471012,23.376384,23.272404,23.221819,23.007852,22.873619,23.151366,-0.025406,0.115376,0.443442,0.305974,0.094628,0.103980,0.050585,-1.784440,-0.605795,5.187697,-1.783851,-0.640220,5.221757,-1.786053,-0.558092,5.249905,-1.709430,-0.639186,5.196217,-1.857198,-0.558281,5.179167,-1.815615,-0.642608,5.141911,-1.793793,-0.556205,5.265406,-1.731166,-0.586967,5.226130,-1.805828,-0.555043,5.134132,-1.870861,-0.585526,5.237546,-1.789714,-0.592624,5.202857,-1.804844,-0.543577,5.215137,-1.812284,-0.565975,5.211059,-1.728014,-0.673926,5.116145,-1.816935,-0.618708,5.166421,-1.741194,-0.622025,5.134105,-1.801676,-0.648010,5.241525,-1.767935,-0.590391,5.189638,-1.815068,-0.556486,5.243816,-1.784236,-0.575317,5.268032,-1.823279,-0.585741,5.201641,-1.778888,-0.598077,5.171472,-1.763825,-0.601896,5.243399,-1.758119,-0.603400,5.191978,-1.744457,-0.587866,5.109130
57,104,149.475722,1.626313,0,0.389645,0.004690,0.015066,0.377765,0.005186,0.014719,0.468260,0.008271,0.018192,0.582758,0.009130,0.016919,1.032440,0.013830,0.014389,1.231677,0.034203,0.028396,1.327044,0.017144,0.013989,1.671119,0.023782,0.016241,1.823997,0.035115,0.021015,2.302721,0.033234,0.019095,2.590386,0.044562,0.022890,1.2817,0,NaN,29,1.01,7,5.709000e+08,0.2,0,-18.94804,-20.47051,-20.73870,9.42859,9.36886,9.49659,9.40345,0.76785,-8.597,24.923327,24.956946,24.723783,24.486279,23.865338,23.673758,23.592787,23.342482,23.247440,22.994396,22.866589,-0.033620,0.233163,0.237504,0.620941,0.191580,0.080971,0.250305,-0.728154,-0.035396,6.708156,-0.740353,-0.091593,6.768124,-0.689050,0.040528,6.732993,-0.672427,-0.064005,6.718223,-0.780927,-0.025928,6.710837,-0.791335,-0.087418,6.661732,-0.737849,-0.020315,6.792989,-0.699331,-0.008417,6.769513,-0.750643,-0.020715,6.679074,-0.819712,-0.049366,6.781445,-0.741962,-0.039734,6.729716,-0.754993,0.020637,6.739427,-0.764083,-0.023137,6.735985,-0.720007,-0.120536,6.683092,-0.809630,-0.073599,6.688920,-0.673522,-0.065116,6.693939,-0.734008,-0.072550,6.732254,-0.696872,-0.043658,6.726207,-0.767533,0.012794,6.770226,-0.739486,-0.030806,6.791350,-0.780993,-0.025780,6.736606,-0.744035,-0.030289,6.712543,-0.725984,-0.018462,6.795384,-0.739205,-0.060440,6.701668,-0.712861,-0.021148,6.679320
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
746927,964392,149.926987,2.376219,0,1.002968,0.007177,0.008954,1.022032,0.005433,0.005699,1.378424,0.007239,0.005408,2.395704,0.007750,0.003493,2.969146,0.012144,0.004393,3.190317,0.025382,0.008135,4.197636,0.051640,0.013321,3.960244,0.068713,0.019800,4.311192,0.049579,0.012554,4.892384,0.016271,0.004400,3.330375,0.016820,0.006720,0.8828,0,NaN,28,1.88,6,5.088000e+08,0.2,1,-19.11129,-20.53859,-20.77834,9.33938,9.30075,9.38472,9.34513,0.79998,-8.569,23.896782,23.876339,23.551543,22.951417,22.718421,22.640415,22.342488,22.405695,22.313507,22.176199,22.593767,0.020444,0.324796,0.600126,0.232996,0.078006,0.297927,-0.063207,-1.270805,-0.038386,2.542257,-1.347991,-0.123391,2.607671,-1.294272,-0.078635,2.624798,-1.229228,-0.051824,2.557802,-1.388296,-0.056294,2.618861,-1.348554,-0.094014,2.595796,-1.331905,-0.040999,2.648559,-1.312359,-0.091873,2.580539,-1.354078,-0.011725,2.556079,-1.391471,-0.064025,2.667527,-1.280693,-0.063183,2.591314,-1.265627,-0.022378,2.532572,-1.363282,-0.083115,2.617853,-1.285658,-0.145150,2.575012,-1.395934,-0.083304,2.577882,-1.302586,-0.099505,2.576342,-1.330812,-0.214038,2.677339,-1.343239,-0.116056,2.565234,-1.364215,-0.081660,2.607933,-1.330275,-0.038184,2.637657,-1.341985,-0.090357,2.625619,-1.298691,-0.108909,2.592449,-1.382676,-0.145920,2.629186,-1.282127,-0.079746,2.628334,-1.293022,-0.057479,2.525704
746931,964398,150.445797,2.041274,0,0.181298,0.005288,0.036389,0.270734,0.003645,0.014400,0.370116,0.004804,0.013344,0.598962,0.005060,0.009111,0.789844,0.008157,0.011083,1.463350,0.017940,0.012525,2.346622,0.013371,0.006166,3.217768,0.017201,0.006098,3.546399,0.024013,0.007390,6.095461,0.013863,0.003009,6.445408,0.014239,0.002939,1.4276,0,NaN,29,1.42,9,2.000000e+09,0.3,1,-18.95152,-21.30856,-22.02227,10.10522,10.06720,10.14134,10.06604,0.91400,-9.135,25.754018,25.318641,24.979156,24.456501,24.156146,23.486630,22.973892,22.631113,22.525531,21.937484,21.876874,0.435377,0.339485,0.522655,0.300355,0.669516,0.512737,0.342779,2.110719,3.080950,8.452576,2.078582,3.126165,8.485680,2.146417,3.143959,8.469193,2.112918,3.151335,8.542129,2.027942,3.099407,8.549092,2.081247,3.074260,8.501442,2.181657,3.087660,8.493359,2.130413,3.124802,8.511638,2.103317,3.070738,8.439727,2.115530,3.087671,8.505279,2.117604,3.072547,8.492297,2.062618,3.117598,8.530201,2.044046,3.085610,8.552464,2.099843,3.036839,8.490396,2.096822,3.064912,8.424489,2.141955,3.091206,8.496152,2.090148,3.063389,8.500201,2.139622,3.109835,8.490760,2.082761,3.088358,8.507909,2.084774,3.119547,8.533949,2.044360,3.099628,8.505398,2.103495,3.110168,8.508243,2.092881,3.125120,8.571184,2.120241,3.091542,8.484233,2.088215,3.158535,8.504679
746932,964399,150.446456,2.041975,0,1.441391,0.007583,0.006564,1.475838,0.005284,0.003829,1.847675,0.006822,0.003796,2.743945,0.007632,0.003000,4.584578,0.012381,0.002898,3.132128,0.025927,0.008457,4.516743,0.019004,0.004553,4.403745,0.024753,0.006412,4.610646,0.034778,0.008232,6.041300,0.015501,0.003394,4.991077,0.016769,0.004470,0.7699,0,NaN,29,1.85,9,1.278000e+08,0.3,0,-19.20053,-20.59380,-20.53390,9.05020,9.01606,9.08420,9.04790,1.30000,-7.731,23.503045,23.477403,23.233436,22.804062,22.246752,22.660401,22.262937,22.290445,22.240596,21.947174,22.154514,0.025642,0.243967,0.429374,0.557310,-0.413649,0.397465,-0.027508,-2.107553,1.210129,-0.091699,-2.159074,1.184871,-0.043516,-2.117182,1.107330,-0.090730,-2.070203,1.183748,-0.079201,-2.196149,1.235389,-0.149250,-2.152356,1.226018,-0.085312,-2.189673,1.197280,-0.015250,-1.999534,1.123159,-0.062411,-2.145166,1.198826,-0.090438,-2.161329,1.272148,0.047234,-2.095147,1.207692,-0.081126,-2.038063,1.198454,-0.054048,-2.147849,1.231387,-0.066484,-2.068470,1.124973,-0.103594,-2.158676,1.281013,-0.083651,-2.135183,1.154055,-0.072507,-2.092787,1.087011,-0.063719,-2.116318,1.164937,-0.046653,-2.104081,1.187621,-0.034149,-2.133029,1.196363,-0.046638,-2.151383,1.110561,-0.085491,-2.082614,1.129197,0.013636,-2.129515,1.184907,-0.059824,-2.068001,1.202488,0.038019,-2.072890,1.193840,-0.066856
746934,964401,150.448750,2.042385,0,0.589872,0.005458,0.011542,0.701791,0.003725,0.005677,1.209010,0.005225,0.004443,1.988288,0.005403,0.002930,2.241010,0.008672,0.004153,2.456919,0.018590,0.007730,3.161674,0.013533,0.004632,3.865762,0.017450,0.005149,4.276106,0.024290,0.006199,NaN,NaN,NaN,NaN,NaN,NaN,0.6936,0,NaN,30,0.51,3,3.602000e+08,0.3,0,-17.99460,-19.79145,-20.19956,9.18869,9.14315,9.23487,9.23363,0.69796,-8.487,24.473106,24.284481,23.693925,23.153802,23.023891,22.924023,22.650207,22.431912,22.322379,NaN,NaN,0.188626,0.590556,0.540123,0.129911,0.099868,0.273816,0.218295,0.614124,3.671981,-0.282331,0.563281,3.612109,-0.218898,0.592076,3.622920,-0.237038,0.630740,3.677824,-0.279946,0.569128,3.630630,-0.256573,0.549735,3.625800,-0.263114,0.550488,3.640552,-0.213028,0.618980,3.612945,-0.257360,0.591285,3.678056,-0.280757,0.530548,3.673424,-0.201614,0.616968,3.686619,-0.227090,0.613414,3.676368,-0.271592,0.592495,3.662101,-0.254063,0.610173,3.621853,-0.305746,0.596353,3.739402,-0.269467,0.562812,3.646034,-0.311863,0.591488,3.589950,-0.250984,0.571116,3.667127,-0.262006,0.546941,3.619303,-0.257750,0.566059,3.679517,-0.220952,0.626304,3.563224,-0.206509,0.541984,3.671294,-0.257031,0.590825,3.663828,-0.226329,0.573387,3.648932,-0.234503,0.663465,3.633038,-0.285643
746938,964405,150.444534,2.041696,0,1.226362,0.005562,0.005659,1.846873,0.004103,0.002376,3.094079,0.005558,0.001847,3.508585,0.005615,0.001726,4.561046,0.008984,0.002114,4.162245,0.018875,0.004633,4.977354,0.014083,0.003062,5.314329,0.018188,0.003904,5.596476,0.025448,0.004963,3.167982,0.013983,0.005839,2.750760,0.013866,0.006707,0.3061,0,NaN,30,0.20,5,1.609000e+09,0.1,1,-16.85576,-18.25674,-18.61250,8.65062,8.61218,8.68845,8.60904,-0.36390,-9.075,23.678453,23.233908,22.673671,22.537170,22.252339,22.351681,22.157504,22.086379,22.030213,22.648043,22.801368,0.444545,0.560236,0.136502,0.284831,-0.099342,0.194177,0.071125,2.169042,10.182035,0.914811,2.155745,10.146915,0.911012,2.088781,10.088406,0.889338,2.141654,10.153145,0.842438,2.198978,10.103227,0.842824,2.177924,10.074351,0.911486,2.151073,10.124307,0.859834,2.091902,10.145029,0.934288,2.133848,10.178343,0.812541,2.166813,10.166430,0.885394,2.130598,10.188725,0.919478,2.230082,10.110093,0.879213,2.195218,10.133659,0.887478,2.255372,10.159369,0.874872,2.300945,10.178132,0.891263,2.184569,10.156761,0.891343,2.201655,10.078734,0.950903,2.147526,10.113942,0.852128,2.137887,10.097965,0.885370,2.116617,10.072495,0.912731,2.234912,10.122618,0.900687,2.204523,10.132223,0.918305,2.151532,10.177387,0.929927,2.146350,10.140948,0.917135,2.152708,10.145682,0.861854

In [27]:
#sizes = [(46,92), (50,100), (54,108)]
#sigmas = [0.85, 1, 1.15]
#learning_rates = [0.68, 0.8, 0.92]
n_embeddings = 25
n_boots = 25

In [28]:
# SOM-tco (SOM-z)
metric='outliers'
somtco_outlier_unc = np.sqrt(somtco_unc_sizeg_outliers**2 + somtco_unc_sigmag_outliers**2 + somtco_unc_lrg_outliers**2 + (somtco_rs_results[metric+'_std'])**2 + (somtco_boots_results[metric+'_std'])**2)
somtco_outlier_unc_lp = np.sqrt(somtco_unc_sizeg_outliers**2 + somtco_unc_sigmag_outliers**2 + somtco_unc_lrg_outliers**2 + (somtco_rs_results[metric+'_std_lp'])**2 + (somtco_boots_results[metric+'_std_lp'])**2)

In [29]:
# colors-kNN-z
metric='outliers'
colors_outlier_unc = np.sqrt(colors_unc_kg_outliers**2 + (colors_boots_results[metric+'_std'])**2)
colors_outlier_unc_lp = np.sqrt(colors_unc_kg_outliers**2 + (colors_boots_results[metric+'_std_lp'])**2)
metric='nmads'
colors_nmad_unc = np.sqrt(colors_unc_kg_nmads**2 + (colors_boots_results[metric+'_std'])**2)
colors_nmad_unc_lp = np.sqrt(colors_unc_kg_nmads**2 + (colors_boots_results[metric+'_std_lp'])**2)
metric='biases'
colors_bias_unc = np.sqrt(colors_unc_kg_biases**2 + (colors_boots_results[metric+'_std'])**2)
colors_bias_unc_lp = np.sqrt(colors_unc_kg_biases**2 + (colors_boots_results[metric+'_std_lp'])**2)

In [30]:
# UMAP-kNN-z
metric='outliers'
umap_outlier_unc = np.sqrt(umap_unc_kg_outliers**2 + umap_unc_nng_outliers**2 + (umap_rs_results[metric+'_std'])**2 + (umap_boots_results[metric+'_std'])**2)
umap_outlier_unc_lp = np.sqrt(umap_unc_kg_outliers**2 + umap_unc_nng_outliers**2 + (umap_rs_results[metric+'_std_lp'])**2 + (umap_boots_results[metric+'_std_lp'])**2)
metric='nmads'
umap_nmad_unc = np.sqrt(umap_unc_kg_nmads**2 + umap_unc_nng_nmads**2 + (umap_rs_results[metric+'_std'])**2 + (umap_boots_results[metric+'_std'])**2)
umap_nmad_unc_lp = np.sqrt(umap_unc_kg_nmads**2 + umap_unc_nng_nmads**2 + (umap_rs_results[metric+'_std_lp'])**2 + (umap_boots_results[metric+'_std_lp'])**2)
metric='biases'
umap_bias_unc = np.sqrt(umap_unc_kg_biases**2 + umap_unc_nng_biases**2 + (umap_rs_results[metric+'_std'])**2 + (umap_boots_results[metric+'_std'])**2)
umap_bias_unc_lp = np.sqrt(umap_unc_kg_biases**2 + umap_unc_nng_biases**2 + (umap_rs_results[metric+'_std_lp'])**2 + (umap_boots_results[metric+'_std_lp'])**2)

### Global Stats w/ Uncertainties

In [31]:
umap_outlier_unc

0.0033562265488944537

In [32]:
global_results = {
    'LePHARE_trained':{
        'f_outlier':{
            'umap_value':umap_rs_results['outliers_mean_lp'],
            'umap_unc':umap_outlier_unc_lp,
            'somtco_value':somtco_rs_results['outliers_mean_lp'],
            'somtco_unc':somtco_outlier_unc_lp,
            'colors_value':colors_rs_results['outliers_mean_lp'],
            'colors_unc':colors_outlier_unc_lp
        },
        'nmad':{
            'umap_value':umap_rs_results['nmads_mean_lp'],
            'umap_unc':umap_nmad_unc_lp,
            'colors_value':colors_rs_results['nmads_mean_lp'],
            'colors_unc':colors_nmad_unc_lp
        },
        'bias':{
            'umap_value':umap_rs_results['biases_mean_lp'],
            'umap_unc':umap_bias_unc_lp,
            'colors_value':colors_rs_results['biases_mean_lp'],
            'colors_unc':colors_bias_unc_lp
        }

    },
    'specz_trained':{
        'f_outlier':{
            'umap_value':umap_rs_results['outliers_mean'],
            'umap_unc':umap_outlier_unc,
            'somtco_value':somtco_rs_results['outliers_mean'],
            'somtco_unc':somtco_outlier_unc,
            'colors_value':colors_rs_results['outliers_mean'],
            'colors_unc':colors_outlier_unc
        },
        'nmad':{
            'umap_value':umap_rs_results['nmads_mean'],
            'umap_unc':umap_nmad_unc,
            'colors_value':colors_rs_results['nmads_mean'],
            'colors_unc':colors_nmad_unc
        },
        'bias':{
            'umap_value':umap_rs_results['biases_mean'],
            'umap_unc':umap_bias_unc,
            'colors_value':colors_rs_results['biases_mean'],
            'colors_unc':colors_bias_unc
        }
    }
}

In [33]:
global_results

{'LePHARE_trained': {'f_outlier': {'umap_value': 0.023265946570997308,
   'umap_unc': 0.0015512928613966779,
   'somtco_value': 0.31907060166313383,
   'somtco_unc': 0.007954960432170768,
   'colors_value': 0.02301700936754052,
   'colors_unc': 0.0013783432441967498},
  'nmad': {'umap_value': 0.02648557041751343,
   'umap_unc': 0.0005854213888087545,
   'colors_value': 0.023819146772277255,
   'colors_unc': 0.00034160487451262574},
  'bias': {'umap_value': -0.015484062408510415,
   'umap_unc': 0.0011913628408477845,
   'colors_value': -0.016969878291300974,
   'colors_unc': 0.0009729923138943153}},
 'specz_trained': {'f_outlier': {'umap_value': 0.025792329442677953,
   'umap_unc': 0.0033562265488944537,
   'somtco_value': 0.6786552132701422,
   'somtco_unc': 0.007932304268423618,
   'colors_value': 0.03207067846729754,
   'colors_unc': 0.002669119097775196},
  'nmad': {'umap_value': 0.027686086050271265,
   'umap_unc': 0.0007621163864343221,
   'colors_value': 0.028132161867484955,
   'colors_unc': 0.0004639072592824503},
  'bias': {'umap_value': -0.02075260926222086,
   'umap_unc': 0.0018707682151898396,
   'colors_value': -0.023453389838367703,
   'colors_unc': 0.0015972282633812675}}}

In [34]:
with open("highz_nonsomtco_missingsom_results_260727.pkl", "wb") as f:
    pickle.dump(global_results, f)